// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/stdlib/errors.proto (package namespace.stdlib, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.stdlib.StatusError
 */
export declare class StatusError extends Message<StatusError> {
  /**
   * @generated from field: int32 code = 1;
   */
  code: number;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated namespace.stdlib.StatusError.Detail details = 3;
   */
  details: StatusError_Detail[];

  constructor(data?: PartialMessage<StatusError>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.stdlib.StatusError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusError;

  static equals(a: StatusError | PlainMessage<StatusError> | undefined, b: StatusError | PlainMessage<StatusError> | undefined): boolean;
}

/**
 * @generated from message namespace.stdlib.StatusError.Detail
 */
export declare class StatusError_Detail extends Message<StatusError_Detail> {
  /**
   * @generated from field: string type_url = 1;
   */
  typeUrl: string;

  /**
   * @generated from field: string serialized_json = 2;
   */
  serializedJson: string;

  /**
   * @generated from field: bytes serialized_proto = 3;
   */
  serializedProto: Uint8Array;

  constructor(data?: PartialMessage<StatusError_Detail>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.stdlib.StatusError.Detail";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StatusError_Detail;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StatusError_Detail;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StatusError_Detail;

  static equals(a: StatusError_Detail | PlainMessage<StatusError_Detail> | undefined, b: StatusError_Detail | PlainMessage<StatusError_Detail> | undefined): boolean;
}

/**
 * @generated from message namespace.stdlib.KnownError
 */
export declare class KnownError extends Message<KnownError> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  constructor(data?: PartialMessage<KnownError>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.stdlib.KnownError";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): KnownError;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): KnownError;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): KnownError;

  static equals(a: KnownError | PlainMessage<KnownError> | undefined, b: KnownError | PlainMessage<KnownError> | undefined): boolean;
}

