// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/stdlib/labels.proto (package namespace.stdlib, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Labels are key/value pairs attached to entities such as tenants.
 *
 * @generated from message namespace.stdlib.Label
 */
export class Label extends Message<Label> {
  /**
   * A name is an string up to 63 bytes that matches the regular expression `^[a-z]([a-z0-9-.]*[a-z0-9])?$`.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Label values are arbitrary values up to 255 bytes.
   *
   * @generated from field: string value = 2;
   */
  value = "";

  constructor(data?: PartialMessage<Label>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.stdlib.Label";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Label {
    return new Label().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Label {
    return new Label().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Label {
    return new Label().fromJsonString(jsonString, options);
  }

  static equals(a: Label | PlainMessage<Label> | undefined, b: Label | PlainMessage<Label> | undefined): boolean {
    return proto3.util.equals(Label, a, b);
  }
}

/**
 * @generated from message namespace.stdlib.LabelFilterEntry
 */
export class LabelFilterEntry extends Message<LabelFilterEntry> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * @generated from field: string value = 2;
   */
  value = "";

  /**
   * @generated from field: namespace.stdlib.LabelFilterEntry.LabelFilterOp op = 3;
   */
  op = LabelFilterEntry_LabelFilterOp.UNKNOWN;

  constructor(data?: PartialMessage<LabelFilterEntry>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.stdlib.LabelFilterEntry";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "op", kind: "enum", T: proto3.getEnumType(LabelFilterEntry_LabelFilterOp) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LabelFilterEntry {
    return new LabelFilterEntry().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LabelFilterEntry {
    return new LabelFilterEntry().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LabelFilterEntry {
    return new LabelFilterEntry().fromJsonString(jsonString, options);
  }

  static equals(a: LabelFilterEntry | PlainMessage<LabelFilterEntry> | undefined, b: LabelFilterEntry | PlainMessage<LabelFilterEntry> | undefined): boolean {
    return proto3.util.equals(LabelFilterEntry, a, b);
  }
}

/**
 * @generated from enum namespace.stdlib.LabelFilterEntry.LabelFilterOp
 */
export enum LabelFilterEntry_LabelFilterOp {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: EQUAL = 1;
   */
  EQUAL = 1,

  /**
   * @generated from enum value: NOT_EQUAL = 2;
   */
  NOT_EQUAL = 2,

  /**
   * @generated from enum value: EXIST = 3;
   */
  EXIST = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(LabelFilterEntry_LabelFilterOp)
proto3.util.setEnumType(LabelFilterEntry_LabelFilterOp, "namespace.stdlib.LabelFilterEntry.LabelFilterOp", [
  { no: 0, name: "UNKNOWN" },
  { no: 1, name: "EQUAL" },
  { no: 2, name: "NOT_EQUAL" },
  { no: 3, name: "EXIST" },
]);

