// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/stdlib/timeseries.proto (package namespace.stdlib, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Represents a time series of data, associating multiple string-keyed data
 * points to each timestamp.
 *
 * Each data point N has a timestamp stored in timestamps[N].
 * Data associated with that timestamp is then stored in:
 * - doubles[key].values[N] if the data is represented as a double
 * - integers[key].values[N] if the data is represented as a int64
 * - strings[key].values[N] if the data is represented as a string
 *
 * The API that returns a TimeSeries describes which keys will be present.
 *
 * @generated from message namespace.stdlib.TimeSeries
 */
export const TimeSeries = proto3.makeMessageType(
  "namespace.stdlib.TimeSeries",
  () => [
    { no: 1, name: "timestamps", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
    { no: 2, name: "doubles", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: TimeSeries_Doubles} },
    { no: 3, name: "integers", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: TimeSeries_Integers} },
    { no: 4, name: "strings", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: TimeSeries_Strings} },
  ],
);

/**
 * @generated from message namespace.stdlib.TimeSeries.Doubles
 */
export const TimeSeries_Doubles = proto3.makeMessageType(
  "namespace.stdlib.TimeSeries.Doubles",
  () => [
    { no: 1, name: "values", kind: "scalar", T: 1 /* ScalarType.DOUBLE */, repeated: true },
  ],
  {localName: "TimeSeries_Doubles"},
);

/**
 * @generated from message namespace.stdlib.TimeSeries.Integers
 */
export const TimeSeries_Integers = proto3.makeMessageType(
  "namespace.stdlib.TimeSeries.Integers",
  () => [
    { no: 1, name: "values", kind: "scalar", T: 3 /* ScalarType.INT64 */, repeated: true },
  ],
  {localName: "TimeSeries_Integers"},
);

/**
 * @generated from message namespace.stdlib.TimeSeries.Strings
 */
export const TimeSeries_Strings = proto3.makeMessageType(
  "namespace.stdlib.TimeSeries.Strings",
  () => [
    { no: 1, name: "values", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
  {localName: "TimeSeries_Strings"},
);

