// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/private/devbox/extra/extra.proto (package namespace.private.devbox.extra.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { EnsureVSCodeRequest, EnsureVSCodeResponse } from "./extra_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service namespace.private.devbox.extra.v1beta.DevBoxExtraService
 */
export declare const DevBoxExtraService: {
  readonly typeName: "namespace.private.devbox.extra.v1beta.DevBoxExtraService",
  readonly methods: {
    /**
     * @generated from rpc namespace.private.devbox.extra.v1beta.DevBoxExtraService.EnsureVSCode
     */
    readonly ensureVSCode: {
      readonly name: "EnsureVSCode",
      readonly I: typeof EnsureVSCodeRequest,
      readonly O: typeof EnsureVSCodeResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

