// @generated by protoc-gen-es v2.11.0 with parameter "target=ts+dts"
// @generated from file proto/namespace/cloud/registry/v1beta/registry.proto (package namespace.cloud.registry.v1beta, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration, EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import type { StringMatcher, TimestampRange } from "../../../stdlib/matchers_pb";
import type { Label } from "../../../stdlib/labels_pb";

/**
 * Describes the file proto/namespace/cloud/registry/v1beta/registry.proto.
 */
export declare const file_proto_namespace_cloud_registry_v1beta_registry: GenFile;

/**
 * @generated from message namespace.cloud.registry.v1beta.ShareImageRequest
 */
export declare type ShareImageRequest = Message<"namespace.cloud.registry.v1beta.ShareImageRequest"> & {
  /**
   * The repository that contains the image to be shared.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;

  /**
   * The digest of the image to be shared.
   *
   * @generated from field: string digest = 2;
   */
  digest: string;

  /**
   * When the shared image should expire. Not setting this results in indefinitely shared images.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  /**
   * Defines who can access this shared image.
   *
   * @generated from field: namespace.cloud.registry.v1beta.Visibility visibility = 4;
   */
  visibility: Visibility;

  /**
   * The optional suffix does not have a practical purpose apart from making the image more operationally distinct.
   * The resulting image reference will, for example, be: public.nscr.io/{meaningful_id}/{suffix}
   *
   * @generated from field: string suffix = 5;
   */
  suffix: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ShareImageRequest.
 * Use `create(ShareImageRequestSchema)` to create a new message.
 */
export declare const ShareImageRequestSchema: GenMessage<ShareImageRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.UnshareImageRequest
 */
export declare type UnshareImageRequest = Message<"namespace.cloud.registry.v1beta.UnshareImageRequest"> & {
  /**
   * The unique identifier of the shared image to unshare.
   *
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.UnshareImageRequest.
 * Use `create(UnshareImageRequestSchema)` to create a new message.
 */
export declare const UnshareImageRequestSchema: GenMessage<UnshareImageRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListSharedImagesRequest
 */
export declare type ListSharedImagesRequest = Message<"namespace.cloud.registry.v1beta.ListSharedImagesRequest"> & {
  /**
   * @generated from field: namespace.stdlib.StringMatcher match_repositories = 1;
   */
  matchRepositories?: StringMatcher;

  /**
   * If set to UNKNOWN_VISIBILITY any image is returned.
   *
   * @generated from field: namespace.cloud.registry.v1beta.Visibility match_visibility = 2;
   */
  matchVisibility: Visibility;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListSharedImagesRequest.
 * Use `create(ListSharedImagesRequestSchema)` to create a new message.
 */
export declare const ListSharedImagesRequestSchema: GenMessage<ListSharedImagesRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListSharedImagesResponse
 */
export declare type ListSharedImagesResponse = Message<"namespace.cloud.registry.v1beta.ListSharedImagesResponse"> & {
  /**
   * @generated from field: repeated namespace.cloud.registry.v1beta.SharedImage shared_images = 1;
   */
  sharedImages: SharedImage[];
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListSharedImagesResponse.
 * Use `create(ListSharedImagesResponseSchema)` to create a new message.
 */
export declare const ListSharedImagesResponseSchema: GenMessage<ListSharedImagesResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.SharedImage
 */
export declare type SharedImage = Message<"namespace.cloud.registry.v1beta.SharedImage"> & {
  /**
   * The unique identifier of this shared image.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The repository that contains the shared image.
   *
   * @generated from field: string shared_repository = 2;
   */
  sharedRepository: string;

  /**
   * The digest of the shared image.
   *
   * @generated from field: string shared_digest = 3;
   */
  sharedDigest: string;

  /**
   * When this shared image expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;

  /**
   * The image reference used to access the shared image.
   *
   * @generated from field: string image_ref = 5;
   */
  imageRef: string;

  /**
   * @generated from field: namespace.cloud.registry.v1beta.Visibility visibility = 6;
   */
  visibility: Visibility;

  /**
   * The suffix that was provided when the shared image got created.
   *
   * @generated from field: string suffix = 7;
   */
  suffix: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.SharedImage.
 * Use `create(SharedImageSchema)` to create a new message.
 */
export declare const SharedImageSchema: GenMessage<SharedImage>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListImagesRequest
 */
export declare type ListImagesRequest = Message<"namespace.cloud.registry.v1beta.ListImagesRequest"> & {
  /**
   * If a previous response returned a `pagination_cursor`, it can be
   * specified to continue reading results with the same arguments as the
   * original call.
   *
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;

  /**
   * The maximum number of entries to return as part of this ListImages
   * request. A maximum number of entries may also be specified when
   * `pagination_cursor` is set.
   *
   * We won't return more than `max_entries`, but may return fewer.
   *
   * @generated from field: int64 max_entries = 2;
   */
  maxEntries: bigint;

  /**
   * Filter images by repository name. If not specified, images from all repositories are returned.
   *
   * @generated from field: namespace.stdlib.StringMatcher match_repository = 3;
   */
  matchRepository?: StringMatcher;

  /**
   * Filter images by creation timestamp range.
   *
   * @generated from field: namespace.stdlib.TimestampRange created_at = 4;
   */
  createdAt?: TimestampRange;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListImagesRequest.
 * Use `create(ListImagesRequestSchema)` to create a new message.
 */
export declare const ListImagesRequestSchema: GenMessage<ListImagesRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListImagesResponse
 */
export declare type ListImagesResponse = Message<"namespace.cloud.registry.v1beta.ListImagesResponse"> & {
  /**
   * @generated from field: repeated namespace.cloud.registry.v1beta.Image images = 1;
   */
  images: Image[];

  /**
   * If set, there are additional results. Pass the same cursor to a
   * subsequent ListImages call to continue fetching results.
   *
   * @generated from field: bytes pagination_cursor = 2;
   */
  paginationCursor: Uint8Array;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListImagesResponse.
 * Use `create(ListImagesResponseSchema)` to create a new message.
 */
export declare const ListImagesResponseSchema: GenMessage<ListImagesResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListRepositoriesRequest
 */
export declare type ListRepositoriesRequest = Message<"namespace.cloud.registry.v1beta.ListRepositoriesRequest"> & {
  /**
   * If a previous response returned a `pagination_cursor`, it can be
   * specified to continue reading results with the same arguments as the
   * original call.
   *
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;

  /**
   * The maximum number of entries to return as part of this ListRepositories
   * request. A maximum number of entries may also be specified when
   * `pagination_cursor` is set.
   *
   * We won't return more than `max_entries`, but may return fewer.
   *
   * @generated from field: int64 max_entries = 2;
   */
  maxEntries: bigint;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListRepositoriesRequest.
 * Use `create(ListRepositoriesRequestSchema)` to create a new message.
 */
export declare const ListRepositoriesRequestSchema: GenMessage<ListRepositoriesRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListRepositoriesResponse
 */
export declare type ListRepositoriesResponse = Message<"namespace.cloud.registry.v1beta.ListRepositoriesResponse"> & {
  /**
   * @generated from field: repeated namespace.cloud.registry.v1beta.Repository repositories = 1;
   */
  repositories: Repository[];

  /**
   * If set, there are additional results. Pass the same cursor to a
   * subsequent ListRepositories call to continue fetching results.
   *
   * @generated from field: bytes pagination_cursor = 2;
   */
  paginationCursor: Uint8Array;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListRepositoriesResponse.
 * Use `create(ListRepositoriesResponseSchema)` to create a new message.
 */
export declare const ListRepositoriesResponseSchema: GenMessage<ListRepositoriesResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.Repository
 */
export declare type Repository = Message<"namespace.cloud.registry.v1beta.Repository"> & {
  /**
   * The name of the repository.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * The timestamp of the last push to this repository.
   *
   * @generated from field: google.protobuf.Timestamp last_push = 2;
   */
  lastPush?: Timestamp;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.Repository.
 * Use `create(RepositorySchema)` to create a new message.
 */
export declare const RepositorySchema: GenMessage<Repository>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListTagsRequest
 */
export declare type ListTagsRequest = Message<"namespace.cloud.registry.v1beta.ListTagsRequest"> & {
  /**
   * If a previous response returned a `pagination_cursor`, it can be
   * specified to continue reading results with the same arguments as the
   * original call.
   *
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;

  /**
   * The maximum number of entries to return as part of this ListTags
   * request. A maximum number of entries may also be specified when
   * `pagination_cursor` is set.
   *
   * We won't return more than `max_entries`, but may return fewer.
   *
   * @generated from field: int64 max_entries = 2;
   */
  maxEntries: bigint;

  /**
   * The repository to list tags from.
   *
   * @generated from field: string repository = 3;
   */
  repository: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListTagsRequest.
 * Use `create(ListTagsRequestSchema)` to create a new message.
 */
export declare const ListTagsRequestSchema: GenMessage<ListTagsRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListTagsResponse
 */
export declare type ListTagsResponse = Message<"namespace.cloud.registry.v1beta.ListTagsResponse"> & {
  /**
   * @generated from field: repeated namespace.cloud.registry.v1beta.Tag tags = 1;
   */
  tags: Tag[];

  /**
   * If set, there are additional results. Pass the same cursor to a
   * subsequent ListTags call to continue fetching results.
   *
   * @generated from field: bytes pagination_cursor = 2;
   */
  paginationCursor: Uint8Array;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListTagsResponse.
 * Use `create(ListTagsResponseSchema)` to create a new message.
 */
export declare const ListTagsResponseSchema: GenMessage<ListTagsResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListTagVersionsRequest
 */
export declare type ListTagVersionsRequest = Message<"namespace.cloud.registry.v1beta.ListTagVersionsRequest"> & {
  /**
   * If a previous response returned a `pagination_cursor`, it can be
   * specified to continue reading results with the same arguments as the
   * original call.
   *
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;

  /**
   * The maximum number of entries to return as part of this ListTagVersions
   * request. A maximum number of entries may also be specified when
   * `pagination_cursor` is set.
   *
   * We won't return more than `max_entries`, but may return fewer.
   *
   * @generated from field: int64 max_entries = 2;
   */
  maxEntries: bigint;

  /**
   * The repository containing the tag.
   *
   * @generated from field: string repository = 3;
   */
  repository: string;

  /**
   * The tag to list versions for.
   *
   * @generated from field: string tag = 4;
   */
  tag: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListTagVersionsRequest.
 * Use `create(ListTagVersionsRequestSchema)` to create a new message.
 */
export declare const ListTagVersionsRequestSchema: GenMessage<ListTagVersionsRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.ListTagVersionsResponse
 */
export declare type ListTagVersionsResponse = Message<"namespace.cloud.registry.v1beta.ListTagVersionsResponse"> & {
  /**
   * The versions of the tag, ordered from newest to oldest.
   *
   * @generated from field: repeated namespace.cloud.registry.v1beta.Tag versions = 1;
   */
  versions: Tag[];

  /**
   * If set, there are additional results. Pass the same cursor to a
   * subsequent ListTagVersions call to continue fetching results.
   *
   * @generated from field: bytes pagination_cursor = 2;
   */
  paginationCursor: Uint8Array;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.ListTagVersionsResponse.
 * Use `create(ListTagVersionsResponseSchema)` to create a new message.
 */
export declare const ListTagVersionsResponseSchema: GenMessage<ListTagVersionsResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.GetImageRequest
 */
export declare type GetImageRequest = Message<"namespace.cloud.registry.v1beta.GetImageRequest"> & {
  /**
   * The repository containing the image.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;

  /**
   * The reference to the image. Can be either a tag or a digest.
   * Digests have the form sha256:<hash>.
   *
   * @generated from field: string reference = 2;
   */
  reference: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.GetImageRequest.
 * Use `create(GetImageRequestSchema)` to create a new message.
 */
export declare const GetImageRequestSchema: GenMessage<GetImageRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.GetImageResponse
 */
export declare type GetImageResponse = Message<"namespace.cloud.registry.v1beta.GetImageResponse"> & {
  /**
   * @generated from field: namespace.cloud.registry.v1beta.Image image = 1;
   */
  image?: Image;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.GetImageResponse.
 * Use `create(GetImageResponseSchema)` to create a new message.
 */
export declare const GetImageResponseSchema: GenMessage<GetImageResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.Image
 */
export declare type Image = Message<"namespace.cloud.registry.v1beta.Image"> & {
  /**
   * The repository containing the image.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;

  /**
   * The digest of the image.
   *
   * @generated from field: string digest = 2;
   */
  digest: string;

  /**
   * When the image was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * When the image expires. Not set if the image does not expire.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 4;
   */
  expiresAt?: Timestamp;

  /**
   * Size information for the image.
   *
   * @generated from field: namespace.cloud.registry.v1beta.Image.Sizes sizes = 5;
   */
  sizes?: Image_Sizes;

  /**
   * If the image has been deleted, when it was deleted.
   *
   * @generated from field: google.protobuf.Timestamp deleted_at = 6;
   */
  deletedAt?: Timestamp;

  /**
   * Labels attached to this image.
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 7;
   */
  labels: Label[];

  /**
   * Tags that reference this image.
   *
   * @generated from field: repeated string tags = 8;
   */
  tags: string[];
};

/**
 * Describes the message namespace.cloud.registry.v1beta.Image.
 * Use `create(ImageSchema)` to create a new message.
 */
export declare const ImageSchema: GenMessage<Image>;

/**
 * @generated from message namespace.cloud.registry.v1beta.Image.Sizes
 */
export declare type Image_Sizes = Message<"namespace.cloud.registry.v1beta.Image.Sizes"> & {
  /**
   * Total size of the image in bytes.
   *
   * @generated from field: int64 total = 1;
   */
  total: bigint;

  /**
   * Size per platform in bytes. Keys are platform identifiers (e.g., "linux/amd64").
   *
   * @generated from field: map<string, int64> per_platform = 2;
   */
  perPlatform: { [key: string]: bigint };
};

/**
 * Describes the message namespace.cloud.registry.v1beta.Image.Sizes.
 * Use `create(Image_SizesSchema)` to create a new message.
 */
export declare const Image_SizesSchema: GenMessage<Image_Sizes>;

/**
 * @generated from message namespace.cloud.registry.v1beta.Tag
 */
export declare type Tag = Message<"namespace.cloud.registry.v1beta.Tag"> & {
  /**
   * The tag name.
   *
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * The image this tag points to.
   *
   * @generated from field: namespace.cloud.registry.v1beta.Image image = 2;
   */
  image?: Image;

  /**
   * When the tag was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.Tag.
 * Use `create(TagSchema)` to create a new message.
 */
export declare const TagSchema: GenMessage<Tag>;

/**
 * @generated from message namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest
 */
export declare type UpdateImageLifetimeRequest = Message<"namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest"> & {
  /**
   * The repository containing the image.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;

  /**
   * The digest of the image of the form sha256:<hash>.
   *
   * @generated from field: string digest = 2;
   */
  digest: string;

  /**
   * The duration the lifetime of this image should be extended by.
   * If the image currently has no expiration then providing extend_by is not supported.
   * Can not be used in combination with new_expiry.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration extend_by = 3;
   */
  extendBy?: Duration;

  /**
   * The minimum remaining duration this image should be alive for.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration ensure_minimum_remaining = 4;
   */
  ensureMinimumRemaining?: Duration;

  /**
   * The new expiration timestamp (in UTC) at which the image expires.
   * Can not be used in combination with extend_by.
   *
   * Note: In JSON format, the Timestamp type is encoded as a string in the
   * [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) format.
   *
   * @generated from field: google.protobuf.Timestamp new_expiry = 5;
   */
  newExpiry?: Timestamp;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.UpdateImageLifetimeRequest.
 * Use `create(UpdateImageLifetimeRequestSchema)` to create a new message.
 */
export declare const UpdateImageLifetimeRequestSchema: GenMessage<UpdateImageLifetimeRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse
 */
export declare type UpdateImageLifetimeResponse = Message<"namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse"> & {
  /**
   * A timestamp at which the image will expire.
   *
   * @generated from field: google.protobuf.Timestamp new_expiry = 1;
   */
  newExpiry?: Timestamp;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.UpdateImageLifetimeResponse.
 * Use `create(UpdateImageLifetimeResponseSchema)` to create a new message.
 */
export declare const UpdateImageLifetimeResponseSchema: GenMessage<UpdateImageLifetimeResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest
 */
export declare type UpdateDefaultPolicyRequest = Message<"namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest"> & {
  /**
   * Only update if revision matches.
   *
   * @generated from field: int64 revision = 1;
   */
  revision: bigint;

  /**
   * The new default expiration duration for newly created images.
   * A duration of at least 4h (=14400s) is required.
   * In order to apply the expiration retroactively to existing images reach out to `support@namespace.so`.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration default_expiration = 2;
   */
  defaultExpiration?: Duration;

  /**
   * Controls whether expiration is enforced.
   *
   * @generated from field: namespace.cloud.registry.v1beta.ExpirationEnforcement expiration_enforcement = 3;
   */
  expirationEnforcement: ExpirationEnforcement;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.UpdateDefaultPolicyRequest.
 * Use `create(UpdateDefaultPolicyRequestSchema)` to create a new message.
 */
export declare const UpdateDefaultPolicyRequestSchema: GenMessage<UpdateDefaultPolicyRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.GetDefaultPolicyResponse
 */
export declare type GetDefaultPolicyResponse = Message<"namespace.cloud.registry.v1beta.GetDefaultPolicyResponse"> & {
  /**
   * The current revision.
   *
   * @generated from field: int64 revision = 1;
   */
  revision: bigint;

  /**
   * The default expiration duration that is applied to newly created images.
   * After this duration the image becomes inaccessible and the underlying blobs are deleted.
   * Not set means no default policy is configured.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration default_expiration = 2;
   */
  defaultExpiration?: Duration;

  /**
   * Controls whether expiration is enforced.
   *
   * @generated from field: namespace.cloud.registry.v1beta.ExpirationEnforcement expiration_enforcement = 3;
   */
  expirationEnforcement: ExpirationEnforcement;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.GetDefaultPolicyResponse.
 * Use `create(GetDefaultPolicyResponseSchema)` to create a new message.
 */
export declare const GetDefaultPolicyResponseSchema: GenMessage<GetDefaultPolicyResponse>;

/**
 * @generated from message namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest
 */
export declare type UpdateRepositoryPolicyRequest = Message<"namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest"> & {
  /**
   * The repository to configure.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;

  /**
   * Only update if revision matches.
   *
   * @generated from field: int64 revision = 2;
   */
  revision: bigint;

  /**
   * The expiration duration for newly created images in this repository.
   * A duration of at least 4h (=14400s) is required.
   * If set, this overrides the default policy for images pushed to this repository.
   * If not set, the default policy is used.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration expiration = 3;
   */
  expiration?: Duration;

  /**
   * Controls whether expiration is enforced for this repository.
   *
   * @generated from field: namespace.cloud.registry.v1beta.ExpirationEnforcement expiration_enforcement = 4;
   */
  expirationEnforcement: ExpirationEnforcement;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.UpdateRepositoryPolicyRequest.
 * Use `create(UpdateRepositoryPolicyRequestSchema)` to create a new message.
 */
export declare const UpdateRepositoryPolicyRequestSchema: GenMessage<UpdateRepositoryPolicyRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest
 */
export declare type GetRepositoryPolicyRequest = Message<"namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest"> & {
  /**
   * The repository to get the policy for.
   *
   * @generated from field: string repository = 1;
   */
  repository: string;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.GetRepositoryPolicyRequest.
 * Use `create(GetRepositoryPolicyRequestSchema)` to create a new message.
 */
export declare const GetRepositoryPolicyRequestSchema: GenMessage<GetRepositoryPolicyRequest>;

/**
 * @generated from message namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse
 */
export declare type GetRepositoryPolicyResponse = Message<"namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse"> & {
  /**
   * The current revision.
   *
   * @generated from field: int64 revision = 1;
   */
  revision: bigint;

  /**
   * The expiration duration that is applied to newly created images in this repository.
   * Not set means the default policy is used.
   *
   * Note: In JSON format, the Duration type is encoded as a string rather than an
   * object, where the string ends in the suffix "s" (indicating seconds) and
   * is preceded by the number of seconds, with nanoseconds expressed as
   * fractional seconds.
   *
   * @generated from field: google.protobuf.Duration expiration = 2;
   */
  expiration?: Duration;

  /**
   * Controls whether expiration is enforced for this repository.
   *
   * @generated from field: namespace.cloud.registry.v1beta.ExpirationEnforcement expiration_enforcement = 3;
   */
  expirationEnforcement: ExpirationEnforcement;
};

/**
 * Describes the message namespace.cloud.registry.v1beta.GetRepositoryPolicyResponse.
 * Use `create(GetRepositoryPolicyResponseSchema)` to create a new message.
 */
export declare const GetRepositoryPolicyResponseSchema: GenMessage<GetRepositoryPolicyResponse>;

/**
 * @generated from enum namespace.cloud.registry.v1beta.Visibility
 */
export enum Visibility {
  /**
   * @generated from enum value: UNKNOWN_VISIBILITY = 0;
   */
  UNKNOWN_VISIBILITY = 0,

  /**
   * Anyone can access the shared image provided they have access to the shared image reference.
   *
   * @generated from enum value: PUBLIC = 1;
   */
  PUBLIC = 1,

  /**
   * Share the image with all tenants of the partner account of the tenant that owns the image.
   *
   * @generated from enum value: PARTNER = 2;
   */
  PARTNER = 2,
}

/**
 * Describes the enum namespace.cloud.registry.v1beta.Visibility.
 */
export declare const VisibilitySchema: GenEnum<Visibility>;

/**
 * Controls whether image expiration is enforced.
 *
 * @generated from enum namespace.cloud.registry.v1beta.ExpirationEnforcement
 */
export enum ExpirationEnforcement {
  /**
   * Default behavior for backwards compatibility:
   * - If expiration is set, it is enforced.
   * - If expiration is not set, it is not enforced.
   *
   * @generated from enum value: EXPIRATION_ENFORCEMENT_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * Expiration is enforced. An expiration duration must be set.
   *
   * @generated from enum value: EXPIRATION_ENFORCEMENT_ENFORCE = 1;
   */
  ENFORCE = 1,

  /**
   * Expiration is not enforced regardless of the expiration duration.
   *
   * @generated from enum value: EXPIRATION_ENFORCEMENT_DO_NOT_ENFORCE = 2;
   */
  DO_NOT_ENFORCE = 2,
}

/**
 * Describes the enum namespace.cloud.registry.v1beta.ExpirationEnforcement.
 */
export declare const ExpirationEnforcementSchema: GenEnum<ExpirationEnforcement>;

/**
 * ContainerRegistryService allows the management of container images stored in
 * the workspace's private container registry (`nscr.io`). It supports listing
 * images and repositories, managing tags, sharing images publicly or with
 * partner accounts, and configuring image expiration policies.
 *
 * See https://namespace.so/docs/architecture/storage/container-registry for an overview.
 *
 * ## Access
 *
 * ContainerRegistryService is a global service that can be accessed at:
 *
 * ```
 * https://global.namespaceapis.com:443
 * ```
 *
 * ## Authentication
 *
 * Calls to the ContainerRegistryService require a *tenant token* passed as a Bearer token as
 * part of each call. These are always required.
 *
 * A *tenant token* identifies both the workspace that the call operates on, but
 * may also constrain the set of actions that the caller may do.
 *
 * A *tenant token* can be obtained using the
 * [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
 *
 * @generated from service namespace.cloud.registry.v1beta.ContainerRegistryService
 */
export declare const ContainerRegistryService: GenService<{
  /**
   * Retrieves a specific image by repository and reference (tag or digest).
   *
   * ### Errors
   * - If the image does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.GetImage
   */
  getImage: {
    methodKind: "unary";
    input: typeof GetImageRequestSchema;
    output: typeof GetImageResponseSchema;
  },
  /**
   * Lists images in the registry that match the specified criteria.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ListImages
   */
  listImages: {
    methodKind: "unary";
    input: typeof ListImagesRequestSchema;
    output: typeof ListImagesResponseSchema;
  },
  /**
   * Lists all repositories in the registry.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ListRepositories
   */
  listRepositories: {
    methodKind: "unary";
    input: typeof ListRepositoriesRequestSchema;
    output: typeof ListRepositoriesResponseSchema;
  },
  /**
   * Lists all tags for a specific repository.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ListTags
   */
  listTags: {
    methodKind: "unary";
    input: typeof ListTagsRequestSchema;
    output: typeof ListTagsResponseSchema;
  },
  /**
   * Lists all versions of a specific tag in a repository, ordered from newest
   * to oldest. A tag can point to different images over time as it is
   * overwritten by new pushes.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ListTagVersions
   */
  listTagVersions: {
    methodKind: "unary";
    input: typeof ListTagVersionsRequestSchema;
    output: typeof ListTagVersionsResponseSchema;
  },
  /**
   * Shares an image either publicly or with tenants of partner accounts.
   * Returns the shared image metadata, including the public image reference
   * that can be used to pull the image.
   *
   * ### Errors
   * - If the image does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ShareImage
   */
  shareImage: {
    methodKind: "unary";
    input: typeof ShareImageRequestSchema;
    output: typeof SharedImageSchema;
  },
  /**
   * Removes an existing share, making the shared image reference inaccessible.
   *
   * ### Errors
   * - If the share does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.UnshareImage
   */
  unshareImage: {
    methodKind: "unary";
    input: typeof UnshareImageRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Lists shared images, optionally filtered by repository and visibility.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.ListSharedImages
   */
  listSharedImages: {
    methodKind: "unary";
    input: typeof ListSharedImagesRequestSchema;
    output: typeof ListSharedImagesResponseSchema;
  },
  /**
   * Extends or updates the expiration of a single image.
   *
   * ### Errors
   * - If the image does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateImageLifetime
   */
  updateImageLifetime: {
    methodKind: "unary";
    input: typeof UpdateImageLifetimeRequestSchema;
    output: typeof UpdateImageLifetimeResponseSchema;
  },
  /**
   * Updates the default image expiration policy for the workspace.
   * The policy applies to newly created images only.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateDefaultPolicy
   */
  updateDefaultPolicy: {
    methodKind: "unary";
    input: typeof UpdateDefaultPolicyRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Returns the current default image expiration policy.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.GetDefaultPolicy
   */
  getDefaultPolicy: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof GetDefaultPolicyResponseSchema;
  },
  /**
   * Updates the image expiration policy for a specific repository.
   * Repository-level policies override the default policy.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.UpdateRepositoryPolicy
   */
  updateRepositoryPolicy: {
    methodKind: "unary";
    input: typeof UpdateRepositoryPolicyRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Returns the current image expiration policy for a specific repository.
   *
   * @generated from rpc namespace.cloud.registry.v1beta.ContainerRegistryService.GetRepositoryPolicy
   */
  getRepositoryPolicy: {
    methodKind: "unary";
    input: typeof GetRepositoryPolicyRequestSchema;
    output: typeof GetRepositoryPolicyResponseSchema;
  },
}>;

