// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/testing/v1beta/testing.proto (package namespace.cloud.testing.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, Duration, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Label } from "../../../stdlib/labels_pb.js";

/**
 * @generated from enum namespace.cloud.testing.v1beta.TestStatus
 */
export declare enum TestStatus {
  /**
   * @generated from enum value: TEST_STATUS_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TEST_STATUS_PASSED = 1;
   */
  PASSED = 1,

  /**
   * @generated from enum value: TEST_STATUS_FAILED = 2;
   */
  FAILED = 2,

  /**
   * @generated from enum value: TEST_STATUS_SKIPPED = 3;
   */
  SKIPPED = 3,

  /**
   * For targets that didn't complete due to build errors, timeouts, etc.
   *
   * @generated from enum value: TEST_STATUS_ERROR = 4;
   */
  ERROR = 4,
}

/**
 * @generated from enum namespace.cloud.testing.v1beta.TestRunStatus
 */
export declare enum TestRunStatus {
  /**
   * @generated from enum value: TEST_RUN_STATUS_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TEST_RUN_STATUS_IN_PROGRESS = 1;
   */
  IN_PROGRESS = 1,

  /**
   * @generated from enum value: TEST_RUN_STATUS_COMPLETED = 2;
   */
  COMPLETED = 2,

  /**
   * @generated from enum value: TEST_RUN_STATUS_FAILED = 3;
   */
  FAILED = 3,

  /**
   * @generated from enum value: TEST_RUN_STATUS_CANCELLED = 4;
   */
  CANCELLED = 4,
}

/**
 * @generated from message namespace.cloud.testing.v1beta.CreateTestRunRequest
 */
export declare class CreateTestRunRequest extends Message<CreateTestRunRequest> {
  /**
   * Optional identifier for the test run (e.g., commit SHA, build ID).
   *
   * @generated from field: string run_identifier = 1;
   */
  runIdentifier: string;

  /**
   * Optional user-provided labels for the test run.
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 2;
   */
  labels: Label[];

  /**
   * Optional environment information.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestEnvironment environment = 3;
   */
  environment?: TestEnvironment;

  constructor(data?: PartialMessage<CreateTestRunRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.CreateTestRunRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTestRunRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTestRunRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTestRunRequest;

  static equals(a: CreateTestRunRequest | PlainMessage<CreateTestRunRequest> | undefined, b: CreateTestRunRequest | PlainMessage<CreateTestRunRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.CreateTestRunResponse
 */
export declare class CreateTestRunResponse extends Message<CreateTestRunResponse> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  constructor(data?: PartialMessage<CreateTestRunResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.CreateTestRunResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateTestRunResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateTestRunResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateTestRunResponse;

  static equals(a: CreateTestRunResponse | PlainMessage<CreateTestRunResponse> | undefined, b: CreateTestRunResponse | PlainMessage<CreateTestRunResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestEnvironment
 */
export declare class TestEnvironment extends Message<TestEnvironment> {
  /**
   * E.g., "linux/amd64", "darwin/arm64"
   *
   * @generated from field: string platform = 1;
   */
  platform: string;

  /**
   * E.g., "go1.21.0", "python3.11"
   *
   * @generated from field: string runtime_version = 2;
   */
  runtimeVersion: string;

  /**
   * Optional environment variables or configuration.
   *
   * @generated from field: map<string, string> properties = 3;
   */
  properties: { [key: string]: string };

  constructor(data?: PartialMessage<TestEnvironment>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestEnvironment";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestEnvironment;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestEnvironment;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestEnvironment;

  static equals(a: TestEnvironment | PlainMessage<TestEnvironment> | undefined, b: TestEnvironment | PlainMessage<TestEnvironment> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.PushTestResultRequest
 */
export declare class PushTestResultRequest extends Message<PushTestResultRequest> {
  /**
   * The run ID returned from CreateTestRun.
   *
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * The test target being reported (e.g., package path, test suite name).
   *
   * @generated from field: string target = 2;
   */
  target: string;

  /**
   * @generated from oneof namespace.cloud.testing.v1beta.PushTestResultRequest.event
   */
  event: {
    /**
     * Signals that a test target has started.
     *
     * @generated from field: namespace.cloud.testing.v1beta.TestTargetStarted started = 3;
     */
    value: TestTargetStarted;
    case: "started";
  } | {
    /**
     * Log entries produced during test execution.
     *
     * @generated from field: namespace.cloud.testing.v1beta.TestLogBatch logs = 4;
     */
    value: TestLogBatch;
    case: "logs";
  } | {
    /**
     * Test case results reported incrementally as they complete.
     *
     * @generated from field: namespace.cloud.testing.v1beta.TestCaseBatch test_cases = 5;
     */
    value: TestCaseBatch;
    case: "testCases";
  } | {
    /**
     * Signals that a test target has completed.
     *
     * @generated from field: namespace.cloud.testing.v1beta.TestTargetCompleted completed = 6;
     */
    value: TestTargetCompleted;
    case: "completed";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<PushTestResultRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.PushTestResultRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushTestResultRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushTestResultRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushTestResultRequest;

  static equals(a: PushTestResultRequest | PlainMessage<PushTestResultRequest> | undefined, b: PushTestResultRequest | PlainMessage<PushTestResultRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestTargetStarted
 */
export declare class TestTargetStarted extends Message<TestTargetStarted> {
  /**
   * When the target started execution.
   *
   * @generated from field: google.protobuf.Timestamp started_at = 1;
   */
  startedAt?: Timestamp;

  /**
   * Optional user-provided labels for this target.
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 2;
   */
  labels: Label[];

  constructor(data?: PartialMessage<TestTargetStarted>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestTargetStarted";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestTargetStarted;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestTargetStarted;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestTargetStarted;

  static equals(a: TestTargetStarted | PlainMessage<TestTargetStarted> | undefined, b: TestTargetStarted | PlainMessage<TestTargetStarted> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestLogBatch
 */
export declare class TestLogBatch extends Message<TestLogBatch> {
  /**
   * Log entries with client-provided IDs for idempotency.
   *
   * @generated from field: repeated namespace.cloud.testing.v1beta.TestLogEntry entries = 1;
   */
  entries: TestLogEntry[];

  constructor(data?: PartialMessage<TestLogBatch>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestLogBatch";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestLogBatch;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestLogBatch;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestLogBatch;

  static equals(a: TestLogBatch | PlainMessage<TestLogBatch> | undefined, b: TestLogBatch | PlainMessage<TestLogBatch> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestCaseBatch
 */
export declare class TestCaseBatch extends Message<TestCaseBatch> {
  /**
   * Test case results reported incrementally.
   *
   * @generated from field: repeated namespace.cloud.testing.v1beta.TestCase test_cases = 1;
   */
  testCases: TestCase[];

  constructor(data?: PartialMessage<TestCaseBatch>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestCaseBatch";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestCaseBatch;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestCaseBatch;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestCaseBatch;

  static equals(a: TestCaseBatch | PlainMessage<TestCaseBatch> | undefined, b: TestCaseBatch | PlainMessage<TestCaseBatch> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestTargetCompleted
 */
export declare class TestTargetCompleted extends Message<TestTargetCompleted> {
  /**
   * Overall status for this target.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestStatus status = 1;
   */
  status: TestStatus;

  /**
   * When the target completed execution.
   *
   * @generated from field: google.protobuf.Timestamp completed_at = 2;
   */
  completedAt?: Timestamp;

  /**
   * Optional user-provided labels for this target.
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 3;
   */
  labels: Label[];

  constructor(data?: PartialMessage<TestTargetCompleted>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestTargetCompleted";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestTargetCompleted;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestTargetCompleted;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestTargetCompleted;

  static equals(a: TestTargetCompleted | PlainMessage<TestTargetCompleted> | undefined, b: TestTargetCompleted | PlainMessage<TestTargetCompleted> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.PushTestResultResponse
 */
export declare class PushTestResultResponse extends Message<PushTestResultResponse> {
  /**
   * The test result ID, returned when available (after started event).
   *
   * @generated from field: string result_id = 1;
   */
  resultId: string;

  constructor(data?: PartialMessage<PushTestResultResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.PushTestResultResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PushTestResultResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PushTestResultResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PushTestResultResponse;

  static equals(a: PushTestResultResponse | PlainMessage<PushTestResultResponse> | undefined, b: PushTestResultResponse | PlainMessage<PushTestResultResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestCase
 */
export declare class TestCase extends Message<TestCase> {
  /**
   * Name of the test case (e.g., "TestFooBar", "test_user_creation").
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Status of this test case.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestStatus status = 2;
   */
  status: TestStatus;

  /**
   * When the test case started execution.
   *
   * @generated from field: google.protobuf.Timestamp started_at = 3;
   */
  startedAt?: Timestamp;

  /**
   * When the test case completed execution.
   *
   * @generated from field: google.protobuf.Timestamp completed_at = 4;
   */
  completedAt?: Timestamp;

  /**
   * Optional error message if the test failed.
   *
   * @generated from field: string error_message = 5;
   */
  errorMessage: string;

  /**
   * Optional stack trace or detailed failure information.
   *
   * @generated from field: string failure_details = 6;
   */
  failureDetails: string;

  /**
   * Optional user-provided labels (e.g., subtest information, parameters).
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 7;
   */
  labels: Label[];

  constructor(data?: PartialMessage<TestCase>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestCase";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestCase;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestCase;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestCase;

  static equals(a: TestCase | PlainMessage<TestCase> | undefined, b: TestCase | PlainMessage<TestCase> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestLogEntry
 */
export declare class TestLogEntry extends Message<TestLogEntry> {
  /**
   * Client-provided unique ID for idempotent insertion.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 2;
   */
  timestamp?: Timestamp;

  /**
   * E.g., "stdout", "stderr"
   *
   * @generated from field: string stream = 3;
   */
  stream: string;

  /**
   * The log content.
   *
   * @generated from field: string content = 4;
   */
  content: string;

  constructor(data?: PartialMessage<TestLogEntry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestLogEntry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestLogEntry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestLogEntry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestLogEntry;

  static equals(a: TestLogEntry | PlainMessage<TestLogEntry> | undefined, b: TestLogEntry | PlainMessage<TestLogEntry> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.LogEntry
 */
export declare class LogEntry extends Message<LogEntry> {
  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;

  /**
   * E.g., "stdout", "stderr"
   *
   * @generated from field: string stream = 2;
   */
  stream: string;

  /**
   * The log content.
   *
   * @generated from field: string content = 3;
   */
  content: string;

  constructor(data?: PartialMessage<LogEntry>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.LogEntry";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): LogEntry;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): LogEntry;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): LogEntry;

  static equals(a: LogEntry | PlainMessage<LogEntry> | undefined, b: LogEntry | PlainMessage<LogEntry> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.StreamTestLogsRequest
 */
export declare class StreamTestLogsRequest extends Message<StreamTestLogsRequest> {
  /**
   * The run ID for this test run.
   *
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * The test target to retrieve logs for.
   *
   * @generated from field: string target = 2;
   */
  target: string;

  constructor(data?: PartialMessage<StreamTestLogsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.StreamTestLogsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTestLogsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTestLogsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTestLogsRequest;

  static equals(a: StreamTestLogsRequest | PlainMessage<StreamTestLogsRequest> | undefined, b: StreamTestLogsRequest | PlainMessage<StreamTestLogsRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.StreamTestLogsChunk
 */
export declare class StreamTestLogsChunk extends Message<StreamTestLogsChunk> {
  /**
   * @generated from field: repeated namespace.cloud.testing.v1beta.LogEntry entries = 1;
   */
  entries: LogEntry[];

  constructor(data?: PartialMessage<StreamTestLogsChunk>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.StreamTestLogsChunk";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): StreamTestLogsChunk;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): StreamTestLogsChunk;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): StreamTestLogsChunk;

  static equals(a: StreamTestLogsChunk | PlainMessage<StreamTestLogsChunk> | undefined, b: StreamTestLogsChunk | PlainMessage<StreamTestLogsChunk> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.CompleteTestRunRequest
 */
export declare class CompleteTestRunRequest extends Message<CompleteTestRunRequest> {
  /**
   * The run ID to mark as complete.
   *
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * Overall status of the test run.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestRunStatus status = 2;
   */
  status: TestRunStatus;

  /**
   * Optional summary information.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestRunSummary summary = 3;
   */
  summary?: TestRunSummary;

  /**
   * Optional completed timestamp. If not provided, defaults to now.
   *
   * @generated from field: google.protobuf.Timestamp completed_at = 4;
   */
  completedAt?: Timestamp;

  constructor(data?: PartialMessage<CompleteTestRunRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.CompleteTestRunRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CompleteTestRunRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CompleteTestRunRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CompleteTestRunRequest;

  static equals(a: CompleteTestRunRequest | PlainMessage<CompleteTestRunRequest> | undefined, b: CompleteTestRunRequest | PlainMessage<CompleteTestRunRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestRunSummary
 */
export declare class TestRunSummary extends Message<TestRunSummary> {
  /**
   * @generated from field: int32 total_targets = 1;
   */
  totalTargets: number;

  /**
   * @generated from field: int32 passed_targets = 2;
   */
  passedTargets: number;

  /**
   * @generated from field: int32 failed_targets = 3;
   */
  failedTargets: number;

  /**
   * @generated from field: int32 skipped_targets = 4;
   */
  skippedTargets: number;

  /**
   * @generated from field: int32 error_targets = 5;
   */
  errorTargets: number;

  /**
   * @generated from field: int32 total_test_cases = 6;
   */
  totalTestCases: number;

  /**
   * @generated from field: int32 passed_test_cases = 7;
   */
  passedTestCases: number;

  /**
   * @generated from field: int32 failed_test_cases = 8;
   */
  failedTestCases: number;

  /**
   * @generated from field: int32 skipped_test_cases = 9;
   */
  skippedTestCases: number;

  /**
   * @generated from field: google.protobuf.Duration total_duration = 10;
   */
  totalDuration?: Duration;

  constructor(data?: PartialMessage<TestRunSummary>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestRunSummary";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestRunSummary;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestRunSummary;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestRunSummary;

  static equals(a: TestRunSummary | PlainMessage<TestRunSummary> | undefined, b: TestRunSummary | PlainMessage<TestRunSummary> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.GetTestRunRequest
 */
export declare class GetTestRunRequest extends Message<GetTestRunRequest> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  constructor(data?: PartialMessage<GetTestRunRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.GetTestRunRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetTestRunRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetTestRunRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetTestRunRequest;

  static equals(a: GetTestRunRequest | PlainMessage<GetTestRunRequest> | undefined, b: GetTestRunRequest | PlainMessage<GetTestRunRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestRun
 */
export declare class TestRun extends Message<TestRun> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: string run_identifier = 2;
   */
  runIdentifier: string;

  /**
   * @generated from field: namespace.cloud.testing.v1beta.TestRunStatus status = 3;
   */
  status: TestRunStatus;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 5;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: namespace.cloud.testing.v1beta.TestEnvironment environment = 6;
   */
  environment?: TestEnvironment;

  /**
   * @generated from field: namespace.cloud.testing.v1beta.TestRunSummary summary = 7;
   */
  summary?: TestRunSummary;

  /**
   * @generated from field: map<string, string> metadata = 8;
   */
  metadata: { [key: string]: string };

  constructor(data?: PartialMessage<TestRun>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestRun";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestRun;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestRun;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestRun;

  static equals(a: TestRun | PlainMessage<TestRun> | undefined, b: TestRun | PlainMessage<TestRun> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.ListTestRunsRequest
 */
export declare class ListTestRunsRequest extends Message<ListTestRunsRequest> {
  /**
   * Optional: filter by run identifier (e.g., commit SHA).
   *
   * @generated from field: string run_identifier = 1;
   */
  runIdentifier: string;

  /**
   * Optional: filter by status.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestRunStatus status = 2;
   */
  status: TestRunStatus;

  /**
   * Optional: maximum number of entries to return.
   *
   * @generated from field: int32 max_entries = 3;
   */
  maxEntries: number;

  /**
   * Optional: only return runs created after this time.
   *
   * @generated from field: google.protobuf.Timestamp created_after = 4;
   */
  createdAfter?: Timestamp;

  /**
   * Optional: only return runs created before this time.
   *
   * @generated from field: google.protobuf.Timestamp created_before = 5;
   */
  createdBefore?: Timestamp;

  constructor(data?: PartialMessage<ListTestRunsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.ListTestRunsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTestRunsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTestRunsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTestRunsRequest;

  static equals(a: ListTestRunsRequest | PlainMessage<ListTestRunsRequest> | undefined, b: ListTestRunsRequest | PlainMessage<ListTestRunsRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.ListTestRunsChunk
 */
export declare class ListTestRunsChunk extends Message<ListTestRunsChunk> {
  /**
   * @generated from field: repeated namespace.cloud.testing.v1beta.TestRun runs = 1;
   */
  runs: TestRun[];

  constructor(data?: PartialMessage<ListTestRunsChunk>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.ListTestRunsChunk";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTestRunsChunk;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTestRunsChunk;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTestRunsChunk;

  static equals(a: ListTestRunsChunk | PlainMessage<ListTestRunsChunk> | undefined, b: ListTestRunsChunk | PlainMessage<ListTestRunsChunk> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.ListTestResultsRequest
 */
export declare class ListTestResultsRequest extends Message<ListTestResultsRequest> {
  /**
   * The run ID to list results for.
   *
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * Optional: filter by target pattern (supports wildcards).
   *
   * @generated from field: string target_pattern = 2;
   */
  targetPattern: string;

  /**
   * Optional: filter by status.
   *
   * @generated from field: namespace.cloud.testing.v1beta.TestStatus status = 3;
   */
  status: TestStatus;

  constructor(data?: PartialMessage<ListTestResultsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.ListTestResultsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTestResultsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTestResultsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTestResultsRequest;

  static equals(a: ListTestResultsRequest | PlainMessage<ListTestResultsRequest> | undefined, b: ListTestResultsRequest | PlainMessage<ListTestResultsRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.ListTestResultsChunk
 */
export declare class ListTestResultsChunk extends Message<ListTestResultsChunk> {
  /**
   * @generated from field: repeated namespace.cloud.testing.v1beta.TestResult results = 1;
   */
  results: TestResult[];

  constructor(data?: PartialMessage<ListTestResultsChunk>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.ListTestResultsChunk";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListTestResultsChunk;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListTestResultsChunk;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListTestResultsChunk;

  static equals(a: ListTestResultsChunk | PlainMessage<ListTestResultsChunk> | undefined, b: ListTestResultsChunk | PlainMessage<ListTestResultsChunk> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.testing.v1beta.TestResult
 */
export declare class TestResult extends Message<TestResult> {
  /**
   * @generated from field: string run_id = 1;
   */
  runId: string;

  /**
   * @generated from field: string target = 2;
   */
  target: string;

  /**
   * @generated from field: namespace.cloud.testing.v1beta.TestStatus status = 3;
   */
  status: TestStatus;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 4;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 5;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Duration duration = 6;
   */
  duration?: Duration;

  /**
   * @generated from field: repeated namespace.cloud.testing.v1beta.TestCase test_cases = 7;
   */
  testCases: TestCase[];

  /**
   * @generated from field: map<string, string> metadata = 8;
   */
  metadata: { [key: string]: string };

  constructor(data?: PartialMessage<TestResult>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.testing.v1beta.TestResult";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TestResult;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TestResult;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TestResult;

  static equals(a: TestResult | PlainMessage<TestResult> | undefined, b: TestResult | PlainMessage<TestResult> | undefined): boolean;
}

