// @generated by protoc-gen-es v2.11.0 with parameter "target=ts+dts"
// @generated from file proto/namespace/cloud/image/v1beta/image.proto (package namespace.cloud.image.v1beta, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file proto/namespace/cloud/image/v1beta/image.proto.
 */
export declare const file_proto_namespace_cloud_image_v1beta_image: GenFile;

/**
 * @generated from message namespace.cloud.image.v1beta.CreateBlueprintRequest
 */
export declare type CreateBlueprintRequest = Message<"namespace.cloud.image.v1beta.CreateBlueprintRequest"> & {
  /**
   * A unique name for the blueprint within the workspace.
   *
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName: string;

  /**
   * The specification that defines how the image is built.
   *
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec spec = 2;
   */
  spec?: BlueprintSpec;
};

/**
 * Describes the message namespace.cloud.image.v1beta.CreateBlueprintRequest.
 * Use `create(CreateBlueprintRequestSchema)` to create a new message.
 */
export declare const CreateBlueprintRequestSchema: GenMessage<CreateBlueprintRequest>;

/**
 * @generated from message namespace.cloud.image.v1beta.CreateBlueprintResponse
 */
export declare type CreateBlueprintResponse = Message<"namespace.cloud.image.v1beta.CreateBlueprintResponse"> & {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;
};

/**
 * Describes the message namespace.cloud.image.v1beta.CreateBlueprintResponse.
 * Use `create(CreateBlueprintResponseSchema)` to create a new message.
 */
export declare const CreateBlueprintResponseSchema: GenMessage<CreateBlueprintResponse>;

/**
 * @generated from message namespace.cloud.image.v1beta.ListBlueprintsRequest
 */
export declare type ListBlueprintsRequest = Message<"namespace.cloud.image.v1beta.ListBlueprintsRequest"> & {
  /**
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;
};

/**
 * Describes the message namespace.cloud.image.v1beta.ListBlueprintsRequest.
 * Use `create(ListBlueprintsRequestSchema)` to create a new message.
 */
export declare const ListBlueprintsRequestSchema: GenMessage<ListBlueprintsRequest>;

/**
 * @generated from message namespace.cloud.image.v1beta.ListBlueprintsResponse
 */
export declare type ListBlueprintsResponse = Message<"namespace.cloud.image.v1beta.ListBlueprintsResponse"> & {
  /**
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor: Uint8Array;

  /**
   * @generated from field: repeated namespace.cloud.image.v1beta.ImageBlueprint blueprints = 2;
   */
  blueprints: ImageBlueprint[];
};

/**
 * Describes the message namespace.cloud.image.v1beta.ListBlueprintsResponse.
 * Use `create(ListBlueprintsResponseSchema)` to create a new message.
 */
export declare const ListBlueprintsResponseSchema: GenMessage<ListBlueprintsResponse>;

/**
 * @generated from message namespace.cloud.image.v1beta.RemoveBlueprintRequest
 */
export declare type RemoveBlueprintRequest = Message<"namespace.cloud.image.v1beta.RemoveBlueprintRequest"> & {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.RemoveBlueprintRequest.
 * Use `create(RemoveBlueprintRequestSchema)` to create a new message.
 */
export declare const RemoveBlueprintRequestSchema: GenMessage<RemoveBlueprintRequest>;

/**
 * @generated from message namespace.cloud.image.v1beta.FetchBlueprintRequest
 */
export declare type FetchBlueprintRequest = Message<"namespace.cloud.image.v1beta.FetchBlueprintRequest"> & {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName: string;

  /**
   * If not provided, the latest blueprint version is used.
   *
   * @generated from field: string blueprint_id = 2;
   */
  blueprintId: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.FetchBlueprintRequest.
 * Use `create(FetchBlueprintRequestSchema)` to create a new message.
 */
export declare const FetchBlueprintRequestSchema: GenMessage<FetchBlueprintRequest>;

/**
 * @generated from message namespace.cloud.image.v1beta.FetchBlueprintResponse
 */
export declare type FetchBlueprintResponse = Message<"namespace.cloud.image.v1beta.FetchBlueprintResponse"> & {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;
};

/**
 * Describes the message namespace.cloud.image.v1beta.FetchBlueprintResponse.
 * Use `create(FetchBlueprintResponseSchema)` to create a new message.
 */
export declare const FetchBlueprintResponseSchema: GenMessage<FetchBlueprintResponse>;

/**
 * @generated from message namespace.cloud.image.v1beta.BuildRequest
 */
export declare type BuildRequest = Message<"namespace.cloud.image.v1beta.BuildRequest"> & {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName: string;

  /**
   * If not provided, the latest blueprint version is used.
   *
   * @generated from field: string blueprint_id = 2;
   */
  blueprintId: string;

  /**
   * Optional: the deployment site to build the image at (e.g. "ord", "iad").
   *
   * @generated from field: string site = 3;
   */
  site: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.BuildRequest.
 * Use `create(BuildRequestSchema)` to create a new message.
 */
export declare const BuildRequestSchema: GenMessage<BuildRequest>;

/**
 * @generated from message namespace.cloud.image.v1beta.BuildResponse
 */
export declare type BuildResponse = Message<"namespace.cloud.image.v1beta.BuildResponse"> & {
  /**
   * The updated blueprint with the new build status.
   *
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;

  /**
   * The image reference of the built image, if the build completed.
   *
   * @generated from field: string image_ref = 2;
   */
  imageRef: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.BuildResponse.
 * Use `create(BuildResponseSchema)` to create a new message.
 */
export declare const BuildResponseSchema: GenMessage<BuildResponse>;

/**
 * An image blueprint defines a reproducible recipe for building container images.
 *
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint
 */
export declare type ImageBlueprint = Message<"namespace.cloud.image.v1beta.ImageBlueprint"> & {
  /**
   * The unique identifier of this blueprint version.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The name of this blueprint.
   *
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * Timestamp of when this blueprint was created (in UTC).
   *
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * Timestamp of when this blueprint was replaced by a newer version (in UTC).
   * Not set if this is the current version.
   *
   * @generated from field: google.protobuf.Timestamp replaced_at = 4;
   */
  replacedAt?: Timestamp;

  /**
   * The specification that defines how the image is built.
   *
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec spec = 5;
   */
  spec?: BlueprintSpec;

  /**
   * The ID of the actor who created this blueprint.
   *
   * @generated from field: string creator_id = 7;
   */
  creatorId: string;

  /**
   * Build state per deployment site (e.g. "ord", "iad").
   *
   * @generated from field: map<string, namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite> state = 8;
   */
  state: { [key: string]: ImageBlueprint_StatePerSite };

  /**
   * Internal metadata version, incremented on each update.
   *
   * @generated from field: int64 metadata_version = 9;
   */
  metadataVersion: bigint;

  /**
   * The most recent build status across all sites.
   *
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint.Status status = 10;
   */
  status?: ImageBlueprint_Status;

  /**
   * Timestamp of when the status was last updated (in UTC).
   *
   * @generated from field: google.protobuf.Timestamp status_updated_at = 11;
   */
  statusUpdatedAt?: Timestamp;
};

/**
 * Describes the message namespace.cloud.image.v1beta.ImageBlueprint.
 * Use `create(ImageBlueprintSchema)` to create a new message.
 */
export declare const ImageBlueprintSchema: GenMessage<ImageBlueprint>;

/**
 * Build state for a specific deployment site.
 *
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite
 */
export declare type ImageBlueprint_StatePerSite = Message<"namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite"> & {
  /**
   * The build state at this site.
   *
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint.State state = 1;
   */
  state: ImageBlueprint_State;

  /**
   * The compute instance ID used for the build, if applicable.
   *
   * @generated from field: string instance_id = 2;
   */
  instanceId: string;

  /**
   * The built image reference at this site, if available.
   *
   * @generated from field: string image_ref = 3;
   */
  imageRef: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite.
 * Use `create(ImageBlueprint_StatePerSiteSchema)` to create a new message.
 */
export declare const ImageBlueprint_StatePerSiteSchema: GenMessage<ImageBlueprint_StatePerSite>;

/**
 * Aggregated build status across all sites.
 *
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint.Status
 */
export declare type ImageBlueprint_Status = Message<"namespace.cloud.image.v1beta.ImageBlueprint.Status"> & {
  /**
   * Timestamp of the last successful build (in UTC).
   *
   * @generated from field: google.protobuf.Timestamp built_at = 1;
   */
  builtAt?: Timestamp;

  /**
   * The image reference of the last successful build.
   *
   * @generated from field: string image_ref = 2;
   */
  imageRef: string;

  /**
   * Timestamp of the last build attempt (in UTC).
   *
   * @generated from field: google.protobuf.Timestamp last_attempt_at = 3;
   */
  lastAttemptAt?: Timestamp;

  /**
   * The builder reference used for the last build attempt.
   *
   * @generated from field: string builder_ref = 4;
   */
  builderRef: string;

  /**
   * Error message from the last failed build attempt.
   *
   * @generated from field: string error = 5;
   */
  error: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.ImageBlueprint.Status.
 * Use `create(ImageBlueprint_StatusSchema)` to create a new message.
 */
export declare const ImageBlueprint_StatusSchema: GenMessage<ImageBlueprint_Status>;

/**
 * @generated from enum namespace.cloud.image.v1beta.ImageBlueprint.State
 */
export enum ImageBlueprint_State {
  /**
   * @generated from enum value: STATE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * The image has been built and is available for use.
   *
   * @generated from enum value: STATE_READY = 1;
   */
  READY = 1,

  /**
   * The blueprint has been created or updated and a build is needed.
   *
   * @generated from enum value: STATE_NEEDS_BUILDING = 2;
   */
  NEEDS_BUILDING = 2,

  /**
   * A build is currently in progress.
   *
   * @generated from enum value: STATE_BUILDING = 3;
   */
  BUILDING = 3,

  /**
   * The most recent build attempt failed.
   *
   * @generated from enum value: STATE_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum namespace.cloud.image.v1beta.ImageBlueprint.State.
 */
export declare const ImageBlueprint_StateSchema: GenEnum<ImageBlueprint_State>;

/**
 * Defines how an image is built. Exactly one source must be specified.
 *
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec
 */
export declare type BlueprintSpec = Message<"namespace.cloud.image.v1beta.BlueprintSpec"> & {
  /**
   * @generated from oneof namespace.cloud.image.v1beta.BlueprintSpec.source
   */
  source: {
    /**
     * Build the image from a Dockerfile.
     *
     * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile dockerfile = 1;
     */
    value: BlueprintSpec_Dockerfile;
    case: "dockerfile";
  } | {
    /**
     * Build the image by installing APT packages on a base image.
     *
     * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage apt_based_image = 2;
     */
    value: BlueprintSpec_AptBasedImage;
    case: "aptBasedImage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message namespace.cloud.image.v1beta.BlueprintSpec.
 * Use `create(BlueprintSpecSchema)` to create a new message.
 */
export declare const BlueprintSpecSchema: GenMessage<BlueprintSpec>;

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile
 */
export declare type BlueprintSpec_Dockerfile = Message<"namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile"> & {
  /**
   * The Dockerfile content used to build the image.
   *
   * @generated from field: string content = 1;
   */
  content: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile.
 * Use `create(BlueprintSpec_DockerfileSchema)` to create a new message.
 */
export declare const BlueprintSpec_DockerfileSchema: GenMessage<BlueprintSpec_Dockerfile>;

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage
 */
export declare type BlueprintSpec_AptBasedImage = Message<"namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage"> & {
  /**
   * The base image to install packages on top of.
   *
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource base_image = 1;
   */
  baseImage?: BlueprintSpec_BaseImageSource;

  /**
   * The list of Ubuntu APT packages to install.
   *
   * @generated from field: repeated string apt_packages = 2;
   */
  aptPackages: string[];
};

/**
 * Describes the message namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage.
 * Use `create(BlueprintSpec_AptBasedImageSchema)` to create a new message.
 */
export declare const BlueprintSpec_AptBasedImageSchema: GenMessage<BlueprintSpec_AptBasedImage>;

/**
 * Defines the base image to use for an APT-based build.
 *
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource
 */
export declare type BlueprintSpec_BaseImageSource = Message<"namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource"> & {
  /**
   * @generated from oneof namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource.source
   */
  source: {
    /**
     * A fully qualified container image reference.
     *
     * @generated from field: string image_ref = 1;
     */
    value: string;
    case: "imageRef";
  } | {
    /**
     * A reference to another blueprint to use as the base.
     *
     * @generated from field: namespace.cloud.image.v1beta.BlueprintRef blueprint_ref = 2;
     */
    value: BlueprintRef;
    case: "blueprintRef";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource.
 * Use `create(BlueprintSpec_BaseImageSourceSchema)` to create a new message.
 */
export declare const BlueprintSpec_BaseImageSourceSchema: GenMessage<BlueprintSpec_BaseImageSource>;

/**
 * References another image blueprint by name and optional version.
 *
 * @generated from message namespace.cloud.image.v1beta.BlueprintRef
 */
export declare type BlueprintRef = Message<"namespace.cloud.image.v1beta.BlueprintRef"> & {
  /**
   * The name of the referenced blueprint.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Optional blueprint version ID. If not provided, uses the latest version.
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message namespace.cloud.image.v1beta.BlueprintRef.
 * Use `create(BlueprintRefSchema)` to create a new message.
 */
export declare const BlueprintRefSchema: GenMessage<BlueprintRef>;

/**
 * ImageService provides container image blueprint management and building.
 * Blueprints define how container images are built (from a Dockerfile or APT
 * packages) and are built asynchronously by the platform.
 *
 * NOTE: This service is still under development and the API is subject to change.
 *
 * ## Access
 *
 * This service is available at the global endpoint:
 *
 * ```
 * https://global.namespaceapis.com:443
 * ```
 *
 * ## Authentication
 *
 * Calls to the ImageService require a *tenant token* passed as a Bearer token
 * as part of each call. These are always required.
 *
 * A *tenant token* identifies both the workspace that the call operates on, but
 * may also constrain the set of actions that the caller may do.
 *
 * A *tenant token* can be obtained using the
 * [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
 *
 * @generated from service namespace.cloud.image.v1beta.ImageService
 */
export declare const ImageService: GenService<{
  /**
   * Creates a new image blueprint with the specified name and specification.
   * Blueprint names must be unique within the workspace.
   *
   * ### Errors
   * - If a blueprint with the same name already exists, an `AlreadyExists`
   *   status is returned.
   * - If the specification is invalid, an `InvalidArgument` status is returned.
   *
   * @generated from rpc namespace.cloud.image.v1beta.ImageService.CreateBlueprint
   */
  createBlueprint: {
    methodKind: "unary";
    input: typeof CreateBlueprintRequestSchema;
    output: typeof CreateBlueprintResponseSchema;
  },
  /**
   * Returns all active blueprints in the workspace.
   *
   * @generated from rpc namespace.cloud.image.v1beta.ImageService.ListBlueprints
   */
  listBlueprints: {
    methodKind: "unary";
    input: typeof ListBlueprintsRequestSchema;
    output: typeof ListBlueprintsResponseSchema;
  },
  /**
   * Removes a blueprint. Existing images built from this blueprint are not
   * affected.
   *
   * ### Errors
   * - If the blueprint does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.image.v1beta.ImageService.RemoveBlueprint
   */
  removeBlueprint: {
    methodKind: "unary";
    input: typeof RemoveBlueprintRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * Retrieves a specific blueprint by name or ID, including its current build
   * status.
   *
   * ### Errors
   * - If the blueprint does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.image.v1beta.ImageService.FetchBlueprint
   */
  fetchBlueprint: {
    methodKind: "unary";
    input: typeof FetchBlueprintRequestSchema;
    output: typeof FetchBlueprintResponseSchema;
  },
  /**
   * Triggers a new build for the specified blueprint. The build is executed
   * asynchronously; use FetchBlueprint to poll for the build status.
   *
   * ### Errors
   * - If the blueprint does not exist, a `NotFound` status is returned.
   *
   * @generated from rpc namespace.cloud.image.v1beta.ImageService.Build
   */
  build: {
    methodKind: "unary";
    input: typeof BuildRequestSchema;
    output: typeof BuildResponseSchema;
  },
}>;

