// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/image/v1beta/image.proto (package namespace.cloud.image.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.cloud.image.v1beta.CreateBlueprintRequest
 */
export class CreateBlueprintRequest extends Message<CreateBlueprintRequest> {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName = "";

  /**
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec spec = 2;
   */
  spec?: BlueprintSpec;

  constructor(data?: PartialMessage<CreateBlueprintRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.CreateBlueprintRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "spec", kind: "message", T: BlueprintSpec },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBlueprintRequest {
    return new CreateBlueprintRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBlueprintRequest {
    return new CreateBlueprintRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBlueprintRequest {
    return new CreateBlueprintRequest().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBlueprintRequest | PlainMessage<CreateBlueprintRequest> | undefined, b: CreateBlueprintRequest | PlainMessage<CreateBlueprintRequest> | undefined): boolean {
    return proto3.util.equals(CreateBlueprintRequest, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.CreateBlueprintResponse
 */
export class CreateBlueprintResponse extends Message<CreateBlueprintResponse> {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;

  constructor(data?: PartialMessage<CreateBlueprintResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.CreateBlueprintResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint", kind: "message", T: ImageBlueprint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateBlueprintResponse {
    return new CreateBlueprintResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateBlueprintResponse {
    return new CreateBlueprintResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateBlueprintResponse {
    return new CreateBlueprintResponse().fromJsonString(jsonString, options);
  }

  static equals(a: CreateBlueprintResponse | PlainMessage<CreateBlueprintResponse> | undefined, b: CreateBlueprintResponse | PlainMessage<CreateBlueprintResponse> | undefined): boolean {
    return proto3.util.equals(CreateBlueprintResponse, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.ListBlueprintsRequest
 */
export class ListBlueprintsRequest extends Message<ListBlueprintsRequest> {
  /**
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor = new Uint8Array(0);

  constructor(data?: PartialMessage<ListBlueprintsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.ListBlueprintsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pagination_cursor", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBlueprintsRequest {
    return new ListBlueprintsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBlueprintsRequest {
    return new ListBlueprintsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBlueprintsRequest {
    return new ListBlueprintsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ListBlueprintsRequest | PlainMessage<ListBlueprintsRequest> | undefined, b: ListBlueprintsRequest | PlainMessage<ListBlueprintsRequest> | undefined): boolean {
    return proto3.util.equals(ListBlueprintsRequest, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.ListBlueprintsResponse
 */
export class ListBlueprintsResponse extends Message<ListBlueprintsResponse> {
  /**
   * @generated from field: bytes pagination_cursor = 1;
   */
  paginationCursor = new Uint8Array(0);

  /**
   * @generated from field: repeated namespace.cloud.image.v1beta.ImageBlueprint blueprints = 2;
   */
  blueprints: ImageBlueprint[] = [];

  constructor(data?: PartialMessage<ListBlueprintsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.ListBlueprintsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "pagination_cursor", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "blueprints", kind: "message", T: ImageBlueprint, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListBlueprintsResponse {
    return new ListBlueprintsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListBlueprintsResponse {
    return new ListBlueprintsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListBlueprintsResponse {
    return new ListBlueprintsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ListBlueprintsResponse | PlainMessage<ListBlueprintsResponse> | undefined, b: ListBlueprintsResponse | PlainMessage<ListBlueprintsResponse> | undefined): boolean {
    return proto3.util.equals(ListBlueprintsResponse, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.RemoveBlueprintRequest
 */
export class RemoveBlueprintRequest extends Message<RemoveBlueprintRequest> {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName = "";

  constructor(data?: PartialMessage<RemoveBlueprintRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.RemoveBlueprintRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RemoveBlueprintRequest {
    return new RemoveBlueprintRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RemoveBlueprintRequest {
    return new RemoveBlueprintRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RemoveBlueprintRequest {
    return new RemoveBlueprintRequest().fromJsonString(jsonString, options);
  }

  static equals(a: RemoveBlueprintRequest | PlainMessage<RemoveBlueprintRequest> | undefined, b: RemoveBlueprintRequest | PlainMessage<RemoveBlueprintRequest> | undefined): boolean {
    return proto3.util.equals(RemoveBlueprintRequest, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.FetchBlueprintRequest
 */
export class FetchBlueprintRequest extends Message<FetchBlueprintRequest> {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName = "";

  /**
   * If not provided, the latest blueprint version is used.
   *
   * @generated from field: string blueprint_id = 2;
   */
  blueprintId = "";

  constructor(data?: PartialMessage<FetchBlueprintRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.FetchBlueprintRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "blueprint_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchBlueprintRequest {
    return new FetchBlueprintRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchBlueprintRequest {
    return new FetchBlueprintRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchBlueprintRequest {
    return new FetchBlueprintRequest().fromJsonString(jsonString, options);
  }

  static equals(a: FetchBlueprintRequest | PlainMessage<FetchBlueprintRequest> | undefined, b: FetchBlueprintRequest | PlainMessage<FetchBlueprintRequest> | undefined): boolean {
    return proto3.util.equals(FetchBlueprintRequest, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.FetchBlueprintResponse
 */
export class FetchBlueprintResponse extends Message<FetchBlueprintResponse> {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;

  constructor(data?: PartialMessage<FetchBlueprintResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.FetchBlueprintResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint", kind: "message", T: ImageBlueprint },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FetchBlueprintResponse {
    return new FetchBlueprintResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FetchBlueprintResponse {
    return new FetchBlueprintResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FetchBlueprintResponse {
    return new FetchBlueprintResponse().fromJsonString(jsonString, options);
  }

  static equals(a: FetchBlueprintResponse | PlainMessage<FetchBlueprintResponse> | undefined, b: FetchBlueprintResponse | PlainMessage<FetchBlueprintResponse> | undefined): boolean {
    return proto3.util.equals(FetchBlueprintResponse, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BuildRequest
 */
export class BuildRequest extends Message<BuildRequest> {
  /**
   * @generated from field: string blueprint_name = 1;
   */
  blueprintName = "";

  /**
   * If not provided, the latest blueprint version is used.
   *
   * @generated from field: string blueprint_id = 2;
   */
  blueprintId = "";

  /**
   * @generated from field: string site = 3;
   */
  site = "";

  constructor(data?: PartialMessage<BuildRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BuildRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "blueprint_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "site", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BuildRequest {
    return new BuildRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BuildRequest {
    return new BuildRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BuildRequest {
    return new BuildRequest().fromJsonString(jsonString, options);
  }

  static equals(a: BuildRequest | PlainMessage<BuildRequest> | undefined, b: BuildRequest | PlainMessage<BuildRequest> | undefined): boolean {
    return proto3.util.equals(BuildRequest, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BuildResponse
 */
export class BuildResponse extends Message<BuildResponse> {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint blueprint = 1;
   */
  blueprint?: ImageBlueprint;

  /**
   * @generated from field: string image_ref = 2;
   */
  imageRef = "";

  constructor(data?: PartialMessage<BuildResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BuildResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "blueprint", kind: "message", T: ImageBlueprint },
    { no: 2, name: "image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BuildResponse {
    return new BuildResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BuildResponse {
    return new BuildResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BuildResponse {
    return new BuildResponse().fromJsonString(jsonString, options);
  }

  static equals(a: BuildResponse | PlainMessage<BuildResponse> | undefined, b: BuildResponse | PlainMessage<BuildResponse> | undefined): boolean {
    return proto3.util.equals(BuildResponse, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint
 */
export class ImageBlueprint extends Message<ImageBlueprint> {
  /**
   * @generated from field: string id = 1;
   */
  id = "";

  /**
   * @generated from field: string name = 2;
   */
  name = "";

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 3;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp replaced_at = 4;
   */
  replacedAt?: Timestamp;

  /**
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec spec = 5;
   */
  spec?: BlueprintSpec;

  /**
   * @generated from field: string creator_id = 7;
   */
  creatorId = "";

  /**
   * State per site.
   *
   * @generated from field: map<string, namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite> state = 8;
   */
  state: { [key: string]: ImageBlueprint_StatePerSite } = {};

  /**
   * @generated from field: int64 metadata_version = 9;
   */
  metadataVersion = protoInt64.zero;

  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint.Status status = 10;
   */
  status?: ImageBlueprint_Status;

  /**
   * @generated from field: google.protobuf.Timestamp status_updated_at = 11;
   */
  statusUpdatedAt?: Timestamp;

  constructor(data?: PartialMessage<ImageBlueprint>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.ImageBlueprint";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "message", T: Timestamp },
    { no: 4, name: "replaced_at", kind: "message", T: Timestamp },
    { no: 5, name: "spec", kind: "message", T: BlueprintSpec },
    { no: 7, name: "creator_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "state", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ImageBlueprint_StatePerSite} },
    { no: 9, name: "metadata_version", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 10, name: "status", kind: "message", T: ImageBlueprint_Status },
    { no: 11, name: "status_updated_at", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImageBlueprint {
    return new ImageBlueprint().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImageBlueprint {
    return new ImageBlueprint().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImageBlueprint {
    return new ImageBlueprint().fromJsonString(jsonString, options);
  }

  static equals(a: ImageBlueprint | PlainMessage<ImageBlueprint> | undefined, b: ImageBlueprint | PlainMessage<ImageBlueprint> | undefined): boolean {
    return proto3.util.equals(ImageBlueprint, a, b);
  }
}

/**
 * @generated from enum namespace.cloud.image.v1beta.ImageBlueprint.State
 */
export enum ImageBlueprint_State {
  /**
   * @generated from enum value: STATE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: STATE_READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: STATE_NEEDS_BUILDING = 2;
   */
  NEEDS_BUILDING = 2,

  /**
   * @generated from enum value: STATE_BUILDING = 3;
   */
  BUILDING = 3,

  /**
   * @generated from enum value: STATE_FAILED = 4;
   */
  FAILED = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(ImageBlueprint_State)
proto3.util.setEnumType(ImageBlueprint_State, "namespace.cloud.image.v1beta.ImageBlueprint.State", [
  { no: 0, name: "STATE_UNKNOWN" },
  { no: 1, name: "STATE_READY" },
  { no: 2, name: "STATE_NEEDS_BUILDING" },
  { no: 3, name: "STATE_BUILDING" },
  { no: 4, name: "STATE_FAILED" },
]);

/**
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite
 */
export class ImageBlueprint_StatePerSite extends Message<ImageBlueprint_StatePerSite> {
  /**
   * @generated from field: namespace.cloud.image.v1beta.ImageBlueprint.State state = 1;
   */
  state = ImageBlueprint_State.UNKNOWN;

  /**
   * @generated from field: string instance_id = 2;
   */
  instanceId = "";

  /**
   * @generated from field: string image_ref = 3;
   */
  imageRef = "";

  constructor(data?: PartialMessage<ImageBlueprint_StatePerSite>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.ImageBlueprint.StatePerSite";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "state", kind: "enum", T: proto3.getEnumType(ImageBlueprint_State) },
    { no: 2, name: "instance_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImageBlueprint_StatePerSite {
    return new ImageBlueprint_StatePerSite().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImageBlueprint_StatePerSite {
    return new ImageBlueprint_StatePerSite().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImageBlueprint_StatePerSite {
    return new ImageBlueprint_StatePerSite().fromJsonString(jsonString, options);
  }

  static equals(a: ImageBlueprint_StatePerSite | PlainMessage<ImageBlueprint_StatePerSite> | undefined, b: ImageBlueprint_StatePerSite | PlainMessage<ImageBlueprint_StatePerSite> | undefined): boolean {
    return proto3.util.equals(ImageBlueprint_StatePerSite, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.ImageBlueprint.Status
 */
export class ImageBlueprint_Status extends Message<ImageBlueprint_Status> {
  /**
   * @generated from field: google.protobuf.Timestamp built_at = 1;
   */
  builtAt?: Timestamp;

  /**
   * @generated from field: string image_ref = 2;
   */
  imageRef = "";

  /**
   * @generated from field: google.protobuf.Timestamp last_attempt_at = 3;
   */
  lastAttemptAt?: Timestamp;

  /**
   * @generated from field: string builder_ref = 4;
   */
  builderRef = "";

  /**
   * @generated from field: string error = 5;
   */
  error = "";

  constructor(data?: PartialMessage<ImageBlueprint_Status>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.ImageBlueprint.Status";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "built_at", kind: "message", T: Timestamp },
    { no: 2, name: "image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "last_attempt_at", kind: "message", T: Timestamp },
    { no: 4, name: "builder_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ImageBlueprint_Status {
    return new ImageBlueprint_Status().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ImageBlueprint_Status {
    return new ImageBlueprint_Status().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ImageBlueprint_Status {
    return new ImageBlueprint_Status().fromJsonString(jsonString, options);
  }

  static equals(a: ImageBlueprint_Status | PlainMessage<ImageBlueprint_Status> | undefined, b: ImageBlueprint_Status | PlainMessage<ImageBlueprint_Status> | undefined): boolean {
    return proto3.util.equals(ImageBlueprint_Status, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec
 */
export class BlueprintSpec extends Message<BlueprintSpec> {
  /**
   * @generated from oneof namespace.cloud.image.v1beta.BlueprintSpec.source
   */
  source: {
    /**
     * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile dockerfile = 1;
     */
    value: BlueprintSpec_Dockerfile;
    case: "dockerfile";
  } | {
    /**
     * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage apt_based_image = 2;
     */
    value: BlueprintSpec_AptBasedImage;
    case: "aptBasedImage";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<BlueprintSpec>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BlueprintSpec";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "dockerfile", kind: "message", T: BlueprintSpec_Dockerfile, oneof: "source" },
    { no: 2, name: "apt_based_image", kind: "message", T: BlueprintSpec_AptBasedImage, oneof: "source" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlueprintSpec {
    return new BlueprintSpec().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlueprintSpec {
    return new BlueprintSpec().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlueprintSpec {
    return new BlueprintSpec().fromJsonString(jsonString, options);
  }

  static equals(a: BlueprintSpec | PlainMessage<BlueprintSpec> | undefined, b: BlueprintSpec | PlainMessage<BlueprintSpec> | undefined): boolean {
    return proto3.util.equals(BlueprintSpec, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile
 */
export class BlueprintSpec_Dockerfile extends Message<BlueprintSpec_Dockerfile> {
  /**
   * @generated from field: string content = 1;
   */
  content = "";

  constructor(data?: PartialMessage<BlueprintSpec_Dockerfile>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BlueprintSpec.Dockerfile";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "content", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlueprintSpec_Dockerfile {
    return new BlueprintSpec_Dockerfile().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlueprintSpec_Dockerfile {
    return new BlueprintSpec_Dockerfile().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlueprintSpec_Dockerfile {
    return new BlueprintSpec_Dockerfile().fromJsonString(jsonString, options);
  }

  static equals(a: BlueprintSpec_Dockerfile | PlainMessage<BlueprintSpec_Dockerfile> | undefined, b: BlueprintSpec_Dockerfile | PlainMessage<BlueprintSpec_Dockerfile> | undefined): boolean {
    return proto3.util.equals(BlueprintSpec_Dockerfile, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage
 */
export class BlueprintSpec_AptBasedImage extends Message<BlueprintSpec_AptBasedImage> {
  /**
   * @generated from field: namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource base_image = 1;
   */
  baseImage?: BlueprintSpec_BaseImageSource;

  /**
   * @generated from field: repeated string apt_packages = 2;
   */
  aptPackages: string[] = [];

  constructor(data?: PartialMessage<BlueprintSpec_AptBasedImage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BlueprintSpec.AptBasedImage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base_image", kind: "message", T: BlueprintSpec_BaseImageSource },
    { no: 2, name: "apt_packages", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlueprintSpec_AptBasedImage {
    return new BlueprintSpec_AptBasedImage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlueprintSpec_AptBasedImage {
    return new BlueprintSpec_AptBasedImage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlueprintSpec_AptBasedImage {
    return new BlueprintSpec_AptBasedImage().fromJsonString(jsonString, options);
  }

  static equals(a: BlueprintSpec_AptBasedImage | PlainMessage<BlueprintSpec_AptBasedImage> | undefined, b: BlueprintSpec_AptBasedImage | PlainMessage<BlueprintSpec_AptBasedImage> | undefined): boolean {
    return proto3.util.equals(BlueprintSpec_AptBasedImage, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource
 */
export class BlueprintSpec_BaseImageSource extends Message<BlueprintSpec_BaseImageSource> {
  /**
   * @generated from oneof namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource.source
   */
  source: {
    /**
     * @generated from field: string image_ref = 1;
     */
    value: string;
    case: "imageRef";
  } | {
    /**
     * @generated from field: namespace.cloud.image.v1beta.BlueprintRef blueprint_ref = 2;
     */
    value: BlueprintRef;
    case: "blueprintRef";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<BlueprintSpec_BaseImageSource>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BlueprintSpec.BaseImageSource";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "source" },
    { no: 2, name: "blueprint_ref", kind: "message", T: BlueprintRef, oneof: "source" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlueprintSpec_BaseImageSource {
    return new BlueprintSpec_BaseImageSource().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlueprintSpec_BaseImageSource {
    return new BlueprintSpec_BaseImageSource().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlueprintSpec_BaseImageSource {
    return new BlueprintSpec_BaseImageSource().fromJsonString(jsonString, options);
  }

  static equals(a: BlueprintSpec_BaseImageSource | PlainMessage<BlueprintSpec_BaseImageSource> | undefined, b: BlueprintSpec_BaseImageSource | PlainMessage<BlueprintSpec_BaseImageSource> | undefined): boolean {
    return proto3.util.equals(BlueprintSpec_BaseImageSource, a, b);
  }
}

/**
 * @generated from message namespace.cloud.image.v1beta.BlueprintRef
 */
export class BlueprintRef extends Message<BlueprintRef> {
  /**
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Optional, if not provided uses latest version
   *
   * @generated from field: string id = 2;
   */
  id = "";

  constructor(data?: PartialMessage<BlueprintRef>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.cloud.image.v1beta.BlueprintRef";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlueprintRef {
    return new BlueprintRef().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlueprintRef {
    return new BlueprintRef().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlueprintRef {
    return new BlueprintRef().fromJsonString(jsonString, options);
  }

  static equals(a: BlueprintRef | PlainMessage<BlueprintRef> | undefined, b: BlueprintRef | PlainMessage<BlueprintRef> | undefined): boolean {
    return proto3.util.equals(BlueprintRef, a, b);
  }
}

