// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/private/instance/instance.proto (package namespace.private.instance.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.private.instance.v1beta.AddAttachmentRequest
 */
export declare class AddAttachmentRequest extends Message<AddAttachmentRequest> {
  /**
   * @generated from field: namespace.private.instance.v1beta.BuildAttachment build_attachment = 1;
   */
  buildAttachment?: BuildAttachment;

  constructor(data?: PartialMessage<AddAttachmentRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.private.instance.v1beta.AddAttachmentRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): AddAttachmentRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): AddAttachmentRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): AddAttachmentRequest;

  static equals(a: AddAttachmentRequest | PlainMessage<AddAttachmentRequest> | undefined, b: AddAttachmentRequest | PlainMessage<AddAttachmentRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.private.instance.v1beta.BuildAttachment
 */
export declare class BuildAttachment extends Message<BuildAttachment> {
  /**
   * @generated from field: string build_ref = 1;
   */
  buildRef: string;

  constructor(data?: PartialMessage<BuildAttachment>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.private.instance.v1beta.BuildAttachment";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BuildAttachment;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BuildAttachment;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BuildAttachment;

  static equals(a: BuildAttachment | PlainMessage<BuildAttachment> | undefined, b: BuildAttachment | PlainMessage<BuildAttachment> | undefined): boolean;
}

