// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/private/instance/instance.proto (package namespace.private.instance.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.private.instance.v1beta.AddAttachmentRequest
 */
export const AddAttachmentRequest = proto3.makeMessageType(
  "namespace.private.instance.v1beta.AddAttachmentRequest",
  () => [
    { no: 1, name: "build_attachment", kind: "message", T: BuildAttachment },
  ],
);

/**
 * @generated from message namespace.private.instance.v1beta.BuildAttachment
 */
export const BuildAttachment = proto3.makeMessageType(
  "namespace.private.instance.v1beta.BuildAttachment",
  () => [
    { no: 1, name: "build_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

