// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/vault/v1beta/vault.proto (package namespace.cloud.vault.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateObjectRequest, DeleteObjectRequest, DescribeObjectRequest, DescribeObjectResponse, ListObjectsRequest, ListObjectsResponse, UpdateObjectRequest, VaultObjectMetadata } from "./vault_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service namespace.cloud.vault.v1beta.VaultService
 */
export const VaultService = {
  typeName: "namespace.cloud.vault.v1beta.VaultService",
  methods: {
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.CreateObject
     */
    createObject: {
      name: "CreateObject",
      I: CreateObjectRequest,
      O: VaultObjectMetadata,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.UpdateObject
     */
    updateObject: {
      name: "UpdateObject",
      I: UpdateObjectRequest,
      O: VaultObjectMetadata,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.DescribeObject
     */
    describeObject: {
      name: "DescribeObject",
      I: DescribeObjectRequest,
      O: DescribeObjectResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.ListObjects
     */
    listObjects: {
      name: "ListObjects",
      I: ListObjectsRequest,
      O: ListObjectsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.DeleteObject
     */
    deleteObject: {
      name: "DeleteObject",
      I: DeleteObjectRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

