// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/vault/v1beta/vault.proto (package namespace.cloud.vault.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateObjectRequest, DeleteObjectRequest, DescribeObjectRequest, DescribeObjectResponse, ListObjectsRequest, ListObjectsResponse, UpdateObjectRequest, VaultObjectMetadata } from "./vault_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service namespace.cloud.vault.v1beta.VaultService
 */
export declare const VaultService: {
  readonly typeName: "namespace.cloud.vault.v1beta.VaultService",
  readonly methods: {
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.CreateObject
     */
    readonly createObject: {
      readonly name: "CreateObject",
      readonly I: typeof CreateObjectRequest,
      readonly O: typeof VaultObjectMetadata,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.UpdateObject
     */
    readonly updateObject: {
      readonly name: "UpdateObject",
      readonly I: typeof UpdateObjectRequest,
      readonly O: typeof VaultObjectMetadata,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.DescribeObject
     */
    readonly describeObject: {
      readonly name: "DescribeObject",
      readonly I: typeof DescribeObjectRequest,
      readonly O: typeof DescribeObjectResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.ListObjects
     */
    readonly listObjects: {
      readonly name: "ListObjects",
      readonly I: typeof ListObjectsRequest,
      readonly O: typeof ListObjectsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc namespace.cloud.vault.v1beta.VaultService.DeleteObject
     */
    readonly deleteObject: {
      readonly name: "DeleteObject",
      readonly I: typeof DeleteObjectRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

