// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/private/devbox/wire/wire.proto (package namespace.private.devbox.wire.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot
 */
export const AgentBoot = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot",
  () => [
    { no: 1, name: "ops", kind: "message", T: AgentBoot_Op, repeated: true },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op
 */
export const AgentBoot_Op = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "setup_namespace_git_credentials", kind: "message", T: AgentBoot_Op_SetupNamespaceGitCredentials },
    { no: 3, name: "git_checkout", kind: "message", T: AgentBoot_Op_GitCheckout },
    { no: 4, name: "git_create_branch", kind: "message", T: AgentBoot_Op_GitCreateBranch },
    { no: 5, name: "git_set_user_and_email", kind: "message", T: AgentBoot_Op_GitSetUserAndEmail },
    { no: 6, name: "run_command", kind: "message", T: AgentBoot_Op_RunCommand },
    { no: 7, name: "run_script", kind: "message", T: AgentBoot_Op_RunScript },
    { no: 8, name: "on_create", kind: "message", T: AgentBoot_Op_OnCreate },
    { no: 9, name: "setup_dotfiles", kind: "message", T: AgentBoot_Op_SetupDotfiles },
    { no: 10, name: "setup_docker", kind: "message", T: AgentBoot_Op_SetupDocker },
  ],
  {localName: "AgentBoot_Op"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupNamespaceGitCredentials
 */
export const AgentBoot_Op_SetupNamespaceGitCredentials = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupNamespaceGitCredentials",
  () => [
    { no: 1, name: "secret_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_SetupNamespaceGitCredentials"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitCheckout
 */
export const AgentBoot_Op_GitCheckout = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitCheckout",
  () => [
    { no: 1, name: "repository", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "workspace_target", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_GitCheckout"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitCreateBranch
 */
export const AgentBoot_Op_GitCreateBranch = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitCreateBranch",
  () => [
    { no: 1, name: "workspace_rel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "branch_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_GitCreateBranch"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitSetUserAndEmail
 */
export const AgentBoot_Op_GitSetUserAndEmail = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.GitSetUserAndEmail",
  [],
  {localName: "AgentBoot_Op_GitSetUserAndEmail"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.RunCommand
 */
export const AgentBoot_Op_RunCommand = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.RunCommand",
  () => [
    { no: 1, name: "cwd", kind: "message", T: AgentBoot_Op_Cwd },
    { no: 2, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "args", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 4, name: "additional_environment", kind: "message", T: AgentBoot_Op_EnvVar, repeated: true },
    { no: 5, name: "stdin", kind: "message", T: AgentBoot_Op_ValueOrSecret },
    { no: 6, name: "run_as", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_RunCommand"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.RunScript
 */
export const AgentBoot_Op_RunScript = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.RunScript",
  () => [
    { no: 1, name: "script", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "additional_environment", kind: "message", T: AgentBoot_Op_EnvVar, repeated: true },
    { no: 3, name: "run_as", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_RunScript"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.OnCreate
 */
export const AgentBoot_Op_OnCreate = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.OnCreate",
  () => [
    { no: 1, name: "ops", kind: "message", T: AgentBoot_Op, repeated: true },
  ],
  {localName: "AgentBoot_Op_OnCreate"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupDotfiles
 */
export const AgentBoot_Op_SetupDotfiles = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupDotfiles",
  () => [
    { no: 1, name: "workspace_target", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_SetupDotfiles"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupDocker
 */
export const AgentBoot_Op_SetupDocker = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.SetupDocker",
  () => [
    { no: 1, name: "docker_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_SetupDocker"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.EnvVar
 */
export const AgentBoot_Op_EnvVar = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.EnvVar",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_EnvVar"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.Cwd
 */
export const AgentBoot_Op_Cwd = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.Cwd",
  () => [
    { no: 1, name: "absolute", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "workspace_relative", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_Cwd"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentBoot.Op.ValueOrSecret
 */
export const AgentBoot_Op_ValueOrSecret = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentBoot.Op.ValueOrSecret",
  () => [
    { no: 1, name: "value", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "from_secret_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentBoot_Op_ValueOrSecret"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentStartup
 */
export const AgentStartup = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentStartup",
  () => [
    { no: 1, name: "repository", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "git_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "git_email", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "port_forwards", kind: "message", T: AgentStartup_PortForward, repeated: true },
    { no: 5, name: "main_user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "shell", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "workspace_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "default_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "user_persistency_dir", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 8, name: "boot", kind: "message", T: AgentBoot },
    { no: 9, name: "authorized_ssh_keys", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 10, name: "bake_image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "include_in_path", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 14, name: "significant_mounts", kind: "message", T: SignificantMount, repeated: true },
    { no: 15, name: "named_ports", kind: "message", T: AgentStartup_NamedPort, repeated: true },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentStartup.PortForward
 */
export const AgentStartup_PortForward = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentStartup.PortForward",
  () => [
    { no: 1, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "label", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "AgentStartup_PortForward"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.AgentStartup.NamedPort
 */
export const AgentStartup_NamedPort = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.AgentStartup.NamedPort",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "port", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
  {localName: "AgentStartup_NamedPort"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.SignificantMount
 */
export const SignificantMount = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.SignificantMount",
  () => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "kind", kind: "enum", T: proto3.getEnumType(SignificantMount_Kind) },
  ],
);

/**
 * @generated from enum namespace.private.devbox.wire.v1beta.SignificantMount.Kind
 */
export const SignificantMount_Kind = proto3.makeEnum(
  "namespace.private.devbox.wire.v1beta.SignificantMount.Kind",
  [
    {no: 0, name: "KIND_UNKNOWN"},
    {no: 1, name: "CACHE_VOLUME"},
    {no: 2, name: "PERSISTENT_VOLUME"},
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.BootOpResult
 */
export const BootOpResult = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.BootOpResult",
  () => [
    { no: 1, name: "op_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "node", kind: "message", T: BootOpResult_Node },
    { no: 3, name: "log", kind: "message", T: BootOpResult_Log, repeated: true },
    { no: 4, name: "result", kind: "message", T: BootOpResult_Result },
    { no: 5, name: "complete", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.BootOpResult.Node
 */
export const BootOpResult_Node = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.BootOpResult.Node",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "op", kind: "message", T: AgentBoot_Op },
  ],
  {localName: "BootOpResult_Node"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.BootOpResult.Log
 */
export const BootOpResult_Log = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.BootOpResult.Log",
  () => [
    { no: 1, name: "stream", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "message", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "BootOpResult_Log"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.BootOpResult.Result
 */
export const BootOpResult_Result = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.BootOpResult.Result",
  () => [
    { no: 1, name: "duration", kind: "message", T: Duration },
    { no: 2, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "BootOpResult_Result"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.StartupState
 */
export const StartupState = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.StartupState",
  () => [
    { no: 1, name: "boot_op_results", kind: "message", T: BootOpResult, repeated: true },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.QueryStateRequest
 */
export const QueryStateRequest = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.QueryStateRequest",
  () => [
    { no: 1, name: "include_git_status", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.QueryStateResponse
 */
export const QueryStateResponse = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.QueryStateResponse",
  () => [
    { no: 1, name: "mount_states", kind: "message", T: QueryStateResponse_SignificantMountState, repeated: true },
    { no: 2, name: "git_status", kind: "message", T: GitStatus },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.QueryStateResponse.SignificantMountState
 */
export const QueryStateResponse_SignificantMountState = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.QueryStateResponse.SignificantMountState",
  () => [
    { no: 1, name: "mount", kind: "message", T: SignificantMount },
    { no: 2, name: "total_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "available_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "free_bytes", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
  ],
  {localName: "QueryStateResponse_SignificantMountState"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.GitStatus
 */
export const GitStatus = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.GitStatus",
  () => [
    { no: 1, name: "current_branch", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tracked_files", kind: "message", T: GitStatus_File, repeated: true },
    { no: 3, name: "untracked_files", kind: "message", T: GitStatus_File, repeated: true },
    { no: 4, name: "local_commits", kind: "message", T: GitStatus_Commit, repeated: true },
  ],
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.GitStatus.File
 */
export const GitStatus_File = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.GitStatus.File",
  () => [
    { no: 1, name: "path", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "lines_added", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "lines_removed", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
  {localName: "GitStatus_File"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.GitStatus.Commit
 */
export const GitStatus_Commit = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.GitStatus.Commit",
  () => [
    { no: 1, name: "digest", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "author", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "author_date", kind: "message", T: Timestamp },
    { no: 5, name: "commit_date", kind: "message", T: Timestamp },
  ],
  {localName: "GitStatus_Commit"},
);

/**
 * @generated from message namespace.private.devbox.wire.v1beta.WebSocketSSHInitiation
 */
export const WebSocketSSHInitiation = proto3.makeMessageType(
  "namespace.private.devbox.wire.v1beta.WebSocketSSHInitiation",
  () => [
    { no: 1, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "private_key", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

