// @generated by protoc-gen-connect-es v0.12.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/storage/v1beta/artifact.proto (package namespace.cloud.storage.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateArtifactRequest, CreateArtifactResponse, ExpireArtifactRequest, FinalizeArtifactRequest, FinalizeArtifactResponse, ListArtifactsRequest, ListArtifactsResponse, ResolveArtifactRequest, ResolveArtifactResponse } from "./artifact_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * ArtifactsService allows the management of artifacts used by a tenant.
 *
 * ## Access
 *
 * ArtifactsService is regionalized for fault tolerance.
 * Reach out to Namespace team at support@namespace.so for a list of available regions.
 *
 * ```
 * https://{region}.storage.namespaceapis.com:443
 * # E.g.:
 * https://ord.storage.namespaceapis.com:443
 * ```
 *
 * ## Authentication
 *
 * Calls to the ArtifactsService require a *tenant token* passed as a Bearer token as
 * part of each call. These are always required.
 *
 * A *tenant token* identifies both the workspace that the call operates on, but
 * may also constrain the set of actions that the caller may do.
 *
 * A *tenant token* can be obtained using the
 * [IAM API](https://buf.build/namespace/cloud/docs/main:namespace.cloud.iam.v1beta).
 *
 * @generated from service namespace.cloud.storage.v1beta.ArtifactsService
 */
export const ArtifactsService = {
  typeName: "namespace.cloud.storage.v1beta.ArtifactsService",
  methods: {
    /**
     * Artifact creation follows a two-phase commit model.
     * Creating an artifact generates an upload URL.
     * After uploading all data, a call to FinalizeArtifact is required to commit the content.
     *
     * @generated from rpc namespace.cloud.storage.v1beta.ArtifactsService.CreateArtifact
     */
    createArtifact: {
      name: "CreateArtifact",
      I: CreateArtifactRequest,
      O: CreateArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Finalize a fully uploaded artifact (making it available for download).
     *
     * @generated from rpc namespace.cloud.storage.v1beta.ArtifactsService.FinalizeArtifact
     */
    finalizeArtifact: {
      name: "FinalizeArtifact",
      I: FinalizeArtifactRequest,
      O: FinalizeArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Resolves a finalized artifact and generates a download URL.
     *
     * @generated from rpc namespace.cloud.storage.v1beta.ArtifactsService.ResolveArtifact
     */
    resolveArtifact: {
      name: "ResolveArtifact",
      I: ResolveArtifactRequest,
      O: ResolveArtifactResponse,
      kind: MethodKind.Unary,
    },
    /**
     * List finalized artifacts.
     *
     * @generated from rpc namespace.cloud.storage.v1beta.ArtifactsService.ListArtifacts
     */
    listArtifacts: {
      name: "ListArtifacts",
      I: ListArtifactsRequest,
      O: ListArtifactsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Mark an artifact as eligible for garbage-collection.
     *
     * @generated from rpc namespace.cloud.storage.v1beta.ArtifactsService.ExpireArtifact
     */
    expireArtifact: {
      name: "ExpireArtifact",
      I: ExpireArtifactRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
};

