// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/storage/v1beta/artifact.proto (package namespace.cloud.storage.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { Label, LabelFilterEntry } from "../../../stdlib/labels_pb.js";

/**
 * @generated from message namespace.cloud.storage.v1beta.CreateArtifactRequest
 */
export declare class CreateArtifactRequest extends Message<CreateArtifactRequest> {
  /**
   * The file path for the artifact to be stored.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * The namespace that the artifact belongs to.
   * Currently, artifact creation outside of the `main` namespace is not permitted.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * Set a custom expiration date for the artifact.
   * If not provided the artifact never expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  /**
   * A set of labels that are attached to the new artifact.
   *
   * @generated from field: repeated namespace.stdlib.Label labels = 5;
   */
  labels: Label[];

  /**
   * Deprecated: please enable versioning using `create_new_version_if_exists`.
   * Whether overwriting an existing artifact with the same path within the same namespace is allowed or not.
   *
   * @generated from field: bool overwrite = 6 [deprecated = true];
   * @deprecated
   */
  overwrite: boolean;

  /**
   * If a version of the artifact already exists, create a new version rather than failing creation.
   *
   * @generated from field: bool create_new_version_if_exists = 7;
   */
  createNewVersionIfExists: boolean;

  constructor(data?: PartialMessage<CreateArtifactRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.CreateArtifactRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateArtifactRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateArtifactRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateArtifactRequest;

  static equals(a: CreateArtifactRequest | PlainMessage<CreateArtifactRequest> | undefined, b: CreateArtifactRequest | PlainMessage<CreateArtifactRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.CreateArtifactResponse
 */
export declare class CreateArtifactResponse extends Message<CreateArtifactResponse> {
  /**
   * @generated from field: string signed_upload_url = 1;
   */
  signedUploadUrl: string;

  /**
   * The identifier for this upload.
   *
   * @generated from field: string upload_id = 2;
   */
  uploadId: string;

  /**
   * The date at which the artifact expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<CreateArtifactResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.CreateArtifactResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateArtifactResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateArtifactResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateArtifactResponse;

  static equals(a: CreateArtifactResponse | PlainMessage<CreateArtifactResponse> | undefined, b: CreateArtifactResponse | PlainMessage<CreateArtifactResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.FinalizeArtifactRequest
 */
export declare class FinalizeArtifactRequest extends Message<FinalizeArtifactRequest> {
  /**
   * @generated from field: string upload_id = 3;
   */
  uploadId: string;

  /**
   * Labels to append to the artifact record.
   *
   * @generated from field: repeated namespace.stdlib.Label add_labels = 4;
   */
  addLabels: Label[];

  /**
   * Unused, upload_id is sufficient.
   *
   * @generated from field: string path = 1 [deprecated = true];
   * @deprecated
   */
  path: string;

  /**
   * Unused, upload_id is sufficient.
   *
   * @generated from field: string namespace = 2 [deprecated = true];
   * @deprecated
   */
  namespace: string;

  constructor(data?: PartialMessage<FinalizeArtifactRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.FinalizeArtifactRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FinalizeArtifactRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FinalizeArtifactRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FinalizeArtifactRequest;

  static equals(a: FinalizeArtifactRequest | PlainMessage<FinalizeArtifactRequest> | undefined, b: FinalizeArtifactRequest | PlainMessage<FinalizeArtifactRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.FinalizeArtifactResponse
 */
export declare class FinalizeArtifactResponse extends Message<FinalizeArtifactResponse> {
  /**
   * @generated from field: namespace.cloud.storage.v1beta.Artifact description = 1;
   */
  description?: Artifact;

  constructor(data?: PartialMessage<FinalizeArtifactResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.FinalizeArtifactResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FinalizeArtifactResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FinalizeArtifactResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FinalizeArtifactResponse;

  static equals(a: FinalizeArtifactResponse | PlainMessage<FinalizeArtifactResponse> | undefined, b: FinalizeArtifactResponse | PlainMessage<FinalizeArtifactResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.ResolveArtifactRequest
 */
export declare class ResolveArtifactRequest extends Message<ResolveArtifactRequest> {
  /**
   * The file path for the stored artifact.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * The namespace that the artifact belongs to.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * Don't produce a download URL; merely query the metadata.
   *
   * @generated from field: bool metadata_only = 3;
   */
  metadataOnly: boolean;

  /**
   * If an expired artifact should be returned or not.
   * If set to false an error is returned.
   *
   * @generated from field: bool include_expired = 4;
   */
  includeExpired: boolean;

  constructor(data?: PartialMessage<ResolveArtifactRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.ResolveArtifactRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResolveArtifactRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResolveArtifactRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResolveArtifactRequest;

  static equals(a: ResolveArtifactRequest | PlainMessage<ResolveArtifactRequest> | undefined, b: ResolveArtifactRequest | PlainMessage<ResolveArtifactRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.ResolveArtifactResponse
 */
export declare class ResolveArtifactResponse extends Message<ResolveArtifactResponse> {
  /**
   * Metadata about the requested artifact.
   *
   * @generated from field: namespace.cloud.storage.v1beta.Artifact description = 3;
   */
  description?: Artifact;

  /**
   * Direct URL to download the artifact without authentication.
   * Valid within 30 minutes from the time of the request.
   *
   * @generated from field: string signed_download_url = 1;
   */
  signedDownloadUrl: string;

  /**
   * The date at which the artifact expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp;

  constructor(data?: PartialMessage<ResolveArtifactResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.ResolveArtifactResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResolveArtifactResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResolveArtifactResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResolveArtifactResponse;

  static equals(a: ResolveArtifactResponse | PlainMessage<ResolveArtifactResponse> | undefined, b: ResolveArtifactResponse | PlainMessage<ResolveArtifactResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.ExpireArtifactRequest
 */
export declare class ExpireArtifactRequest extends Message<ExpireArtifactRequest> {
  /**
   * The file path for the stored artifact.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * The namespace that the artifact belongs to.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  constructor(data?: PartialMessage<ExpireArtifactRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.ExpireArtifactRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ExpireArtifactRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ExpireArtifactRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ExpireArtifactRequest;

  static equals(a: ExpireArtifactRequest | PlainMessage<ExpireArtifactRequest> | undefined, b: ExpireArtifactRequest | PlainMessage<ExpireArtifactRequest> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.ListArtifactsRequest
 */
export declare class ListArtifactsRequest extends Message<ListArtifactsRequest> {
  /**
   * If set, only return artifacts that belong to any of these namespaces.
   *
   * @generated from field: repeated string namespaces = 1;
   */
  namespaces: string[];

  /**
   * Only return artifacts that match the specified filter.
   *
   * @generated from field: repeated namespace.stdlib.LabelFilterEntry label_filter = 2;
   */
  labelFilter: LabelFilterEntry[];

  /**
   * Request a maximum N entries.
   *
   * @generated from field: int32 max_entries = 3;
   */
  maxEntries: number;

  /**
   * Don't return expired entries.
   *
   * @generated from field: bool skip_expired = 5;
   */
  skipExpired: boolean;

  /**
   * If provided, produces additional entries based on a previous list. In
   * this case, `namespaces` amd `label_filter` are ignored.
   *
   * @generated from field: bytes pagination_cursor = 4;
   */
  paginationCursor: Uint8Array;

  /**
   * @generated from field: namespace.cloud.storage.v1beta.ListArtifactsRequest.OrderBy order_by = 6;
   */
  orderBy: ListArtifactsRequest_OrderBy;

  constructor(data?: PartialMessage<ListArtifactsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.ListArtifactsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtifactsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtifactsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtifactsRequest;

  static equals(a: ListArtifactsRequest | PlainMessage<ListArtifactsRequest> | undefined, b: ListArtifactsRequest | PlainMessage<ListArtifactsRequest> | undefined): boolean;
}

/**
 * @generated from enum namespace.cloud.storage.v1beta.ListArtifactsRequest.OrderBy
 */
export declare enum ListArtifactsRequest_OrderBy {
  /**
   * @generated from enum value: ORDER_BY_UNKNOWN = 0;
   */
  ORDER_BY_UNKNOWN = 0,

  /**
   * @generated from enum value: CreatedAt_Desc = 1;
   */
  CreatedAt_Desc = 1,
}

/**
 * @generated from message namespace.cloud.storage.v1beta.ListArtifactsResponse
 */
export declare class ListArtifactsResponse extends Message<ListArtifactsResponse> {
  /**
   * @generated from field: repeated namespace.cloud.storage.v1beta.Artifact artifacts = 1;
   */
  artifacts: Artifact[];

  /**
   * Pass this to a subsequent ListRequest to obtain additional pages of data.
   *
   * @generated from field: bytes pagination_cursor = 2;
   */
  paginationCursor: Uint8Array;

  constructor(data?: PartialMessage<ListArtifactsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.ListArtifactsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListArtifactsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListArtifactsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListArtifactsResponse;

  static equals(a: ListArtifactsResponse | PlainMessage<ListArtifactsResponse> | undefined, b: ListArtifactsResponse | PlainMessage<ListArtifactsResponse> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.storage.v1beta.Artifact
 */
export declare class Artifact extends Message<Artifact> {
  /**
   * @generated from field: string id = 10;
   */
  id: string;

  /**
   * The file path for the stored artifact.
   *
   * @generated from field: string path = 1;
   */
  path: string;

  /**
   * The namespace that the artifact belongs to.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;

  /**
   * The date at which the artifact was created.
   *
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;

  /**
   * The date at which the artifact expires.
   *
   * @generated from field: google.protobuf.Timestamp expires_at = 3;
   */
  expiresAt?: Timestamp;

  /**
   * @generated from field: repeated namespace.stdlib.Label labels = 5;
   */
  labels: Label[];

  /**
   * The size of the uploaded data in bytes.
   *
   * @generated from field: int64 size = 7;
   */
  size: bigint;

  /**
   * URL to the dashboard for this artifact.
   *
   * @generated from field: string web_url = 8;
   */
  webUrl: string;

  /**
   * In which state this artifact is.
   *
   * @generated from field: namespace.cloud.storage.v1beta.Artifact.Status status = 9;
   */
  status: Artifact_Status;

  constructor(data?: PartialMessage<Artifact>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.storage.v1beta.Artifact";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Artifact;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Artifact;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Artifact;

  static equals(a: Artifact | PlainMessage<Artifact> | undefined, b: Artifact | PlainMessage<Artifact> | undefined): boolean;
}

/**
 * @generated from enum namespace.cloud.storage.v1beta.Artifact.Status
 */
export declare enum Artifact_Status {
  /**
   * @generated from enum value: STATE_UNKNOWN = 0;
   */
  STATE_UNKNOWN = 0,

  /**
   * @generated from enum value: LIVE = 1;
   */
  LIVE = 1,

  /**
   * @generated from enum value: EXPIRED = 2;
   */
  EXPIRED = 2,
}

