// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/compute/v1beta/limits.proto (package namespace.cloud.compute.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy
 */
export declare class UsagePolicy extends Message<UsagePolicy> {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits concurrency_limits = 1;
   */
  concurrencyLimits?: UsagePolicy_ConcurrencyLimits;

  /**
   * In a period.
   *
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits usage_limits = 2;
   */
  usageLimits?: UsagePolicy_UsageLimits;

  /**
   * E.g. linux/arm64, linux/amd64, macos/arm64
   *
   * @generated from field: repeated string enabled_platforms = 3;
   */
  enabledPlatforms: string[];

  /**
   * Key is linux/amd64, linux/arm64 or macos/arm64.
   *
   * @generated from field: map<string, namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits> per_platform_limits = 4;
   */
  perPlatformLimits: { [key: string]: UsagePolicy_PerPlatformLimits };

  constructor(data?: PartialMessage<UsagePolicy>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy;

  static equals(a: UsagePolicy | PlainMessage<UsagePolicy> | undefined, b: UsagePolicy | PlainMessage<UsagePolicy> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits
 */
export declare class UsagePolicy_ConcurrencyLimits extends Message<UsagePolicy_ConcurrencyLimits> {
  /**
   * @generated from field: int64 max_cpu = 1;
   */
  maxCpu: bigint;

  /**
   * @generated from field: int64 max_memory_mb = 2;
   */
  maxMemoryMb: bigint;

  /**
   * @generated from field: int64 max_instance_count = 3;
   */
  maxInstanceCount: bigint;

  constructor(data?: PartialMessage<UsagePolicy_ConcurrencyLimits>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_ConcurrencyLimits;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_ConcurrencyLimits;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_ConcurrencyLimits;

  static equals(a: UsagePolicy_ConcurrencyLimits | PlainMessage<UsagePolicy_ConcurrencyLimits> | undefined, b: UsagePolicy_ConcurrencyLimits | PlainMessage<UsagePolicy_ConcurrencyLimits> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits
 */
export declare class UsagePolicy_UsageLimits extends Message<UsagePolicy_UsageLimits> {
  /**
   * @generated from field: int32 unit_minutes = 1;
   */
  unitMinutes: number;

  /**
   * @generated from field: int32 builds = 2;
   */
  builds: number;

  /**
   * @generated from field: int64 wall_seconds = 3;
   */
  wallSeconds: bigint;

  constructor(data?: PartialMessage<UsagePolicy_UsageLimits>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_UsageLimits;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_UsageLimits;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_UsageLimits;

  static equals(a: UsagePolicy_UsageLimits | PlainMessage<UsagePolicy_UsageLimits> | undefined, b: UsagePolicy_UsageLimits | PlainMessage<UsagePolicy_UsageLimits> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits
 */
export declare class UsagePolicy_ShapeLimits extends Message<UsagePolicy_ShapeLimits> {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize largest_acceptable_shape = 1;
   */
  largestAcceptableShape?: UsagePolicy_MachineShapeSize;

  constructor(data?: PartialMessage<UsagePolicy_ShapeLimits>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_ShapeLimits;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_ShapeLimits;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_ShapeLimits;

  static equals(a: UsagePolicy_ShapeLimits | PlainMessage<UsagePolicy_ShapeLimits> | undefined, b: UsagePolicy_ShapeLimits | PlainMessage<UsagePolicy_ShapeLimits> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits
 */
export declare class UsagePolicy_PerPlatformLimits extends Message<UsagePolicy_PerPlatformLimits> {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits concurrency_limits = 1;
   */
  concurrencyLimits?: UsagePolicy_ConcurrencyLimits;

  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits shape_limits = 2;
   */
  shapeLimits?: UsagePolicy_ShapeLimits;

  /**
   * List of per-shape concurrency limits.
   *
   * @generated from field: repeated namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits per_shape_limits = 3;
   */
  perShapeLimits: UsagePolicy_PerShapeLimits[];

  constructor(data?: PartialMessage<UsagePolicy_PerPlatformLimits>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_PerPlatformLimits;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_PerPlatformLimits;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_PerPlatformLimits;

  static equals(a: UsagePolicy_PerPlatformLimits | PlainMessage<UsagePolicy_PerPlatformLimits> | undefined, b: UsagePolicy_PerPlatformLimits | PlainMessage<UsagePolicy_PerPlatformLimits> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize
 */
export declare class UsagePolicy_MachineShapeSize extends Message<UsagePolicy_MachineShapeSize> {
  /**
   * @generated from field: int64 cpu = 1;
   */
  cpu: bigint;

  /**
   * @generated from field: int64 memory_mb = 2;
   */
  memoryMb: bigint;

  constructor(data?: PartialMessage<UsagePolicy_MachineShapeSize>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_MachineShapeSize;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_MachineShapeSize;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_MachineShapeSize;

  static equals(a: UsagePolicy_MachineShapeSize | PlainMessage<UsagePolicy_MachineShapeSize> | undefined, b: UsagePolicy_MachineShapeSize | PlainMessage<UsagePolicy_MachineShapeSize> | undefined): boolean;
}

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits
 */
export declare class UsagePolicy_PerShapeLimits extends Message<UsagePolicy_PerShapeLimits> {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize shape = 1;
   */
  shape?: UsagePolicy_MachineShapeSize;

  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits limits = 2;
   */
  limits?: UsagePolicy_ConcurrencyLimits;

  constructor(data?: PartialMessage<UsagePolicy_PerShapeLimits>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UsagePolicy_PerShapeLimits;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UsagePolicy_PerShapeLimits;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UsagePolicy_PerShapeLimits;

  static equals(a: UsagePolicy_PerShapeLimits | PlainMessage<UsagePolicy_PerShapeLimits> | undefined, b: UsagePolicy_PerShapeLimits | PlainMessage<UsagePolicy_PerShapeLimits> | undefined): boolean;
}

