// @generated by protoc-gen-es v2.11.0 with parameter "target=ts+dts,import_extension=js"
// @generated from file proto/namespace/cloud/compute/v1beta/limits.proto (package namespace.cloud.compute.v1beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/namespace/cloud/compute/v1beta/limits.proto.
 */
export const file_proto_namespace_cloud_compute_v1beta_limits: GenFile = /*@__PURE__*/
  fileDesc("CjFwcm90by9uYW1lc3BhY2UvY2xvdWQvY29tcHV0ZS92MWJldGEvbGltaXRzLnByb3RvEh5uYW1lc3BhY2UuY2xvdWQuY29tcHV0ZS52MWJldGEiuAkKC1VzYWdlUG9saWN5ElkKEmNvbmN1cnJlbmN5X2xpbWl0cxgBIAEoCzI9Lm5hbWVzcGFjZS5jbG91ZC5jb21wdXRlLnYxYmV0YS5Vc2FnZVBvbGljeS5Db25jdXJyZW5jeUxpbWl0cxJNCgx1c2FnZV9saW1pdHMYAiABKAsyNy5uYW1lc3BhY2UuY2xvdWQuY29tcHV0ZS52MWJldGEuVXNhZ2VQb2xpY3kuVXNhZ2VMaW1pdHMSGQoRZW5hYmxlZF9wbGF0Zm9ybXMYAyADKAkSXwoTcGVyX3BsYXRmb3JtX2xpbWl0cxgEIAMoCzJCLm5hbWVzcGFjZS5jbG91ZC5jb21wdXRlLnYxYmV0YS5Vc2FnZVBvbGljeS5QZXJQbGF0Zm9ybUxpbWl0c0VudHJ5GncKFlBlclBsYXRmb3JtTGltaXRzRW50cnkSCwoDa2V5GAEgASgJEkwKBXZhbHVlGAIgASgLMj0ubmFtZXNwYWNlLmNsb3VkLmNvbXB1dGUudjFiZXRhLlVzYWdlUG9saWN5LlBlclBsYXRmb3JtTGltaXRzOgI4ARpXChFDb25jdXJyZW5jeUxpbWl0cxIPCgdtYXhfY3B1GAEgASgDEhUKDW1heF9tZW1vcnlfbWIYAiABKAMSGgoSbWF4X2luc3RhbmNlX2NvdW50GAMgASgDGkkKC1VzYWdlTGltaXRzEhQKDHVuaXRfbWludXRlcxgBIAEoBRIOCgZidWlsZHMYAiABKAUSFAoMd2FsbF9zZWNvbmRzGAMgASgDGm0KC1NoYXBlTGltaXRzEl4KGGxhcmdlc3RfYWNjZXB0YWJsZV9zaGFwZRgBIAEoCzI8Lm5hbWVzcGFjZS5jbG91ZC5jb21wdXRlLnYxYmV0YS5Vc2FnZVBvbGljeS5NYWNoaW5lU2hhcGVTaXplGpMCChFQZXJQbGF0Zm9ybUxpbWl0cxJZChJjb25jdXJyZW5jeV9saW1pdHMYASABKAsyPS5uYW1lc3BhY2UuY2xvdWQuY29tcHV0ZS52MWJldGEuVXNhZ2VQb2xpY3kuQ29uY3VycmVuY3lMaW1pdHMSTQoMc2hhcGVfbGltaXRzGAIgASgLMjcubmFtZXNwYWNlLmNsb3VkLmNvbXB1dGUudjFiZXRhLlVzYWdlUG9saWN5LlNoYXBlTGltaXRzElQKEHBlcl9zaGFwZV9saW1pdHMYAyADKAsyOi5uYW1lc3BhY2UuY2xvdWQuY29tcHV0ZS52MWJldGEuVXNhZ2VQb2xpY3kuUGVyU2hhcGVMaW1pdHMaMgoQTWFjaGluZVNoYXBlU2l6ZRILCgNjcHUYASABKAMSEQoJbWVtb3J5X21iGAIgASgDGqwBCg5QZXJTaGFwZUxpbWl0cxJLCgVzaGFwZRgBIAEoCzI8Lm5hbWVzcGFjZS5jbG91ZC5jb21wdXRlLnYxYmV0YS5Vc2FnZVBvbGljeS5NYWNoaW5lU2hhcGVTaXplEk0KBmxpbWl0cxgCIAEoCzI9Lm5hbWVzcGFjZS5jbG91ZC5jb21wdXRlLnYxYmV0YS5Vc2FnZVBvbGljeS5Db25jdXJyZW5jeUxpbWl0c0JMWkpuYW1lc3BhY2VsYWJzLmRldi9pbnRlcm5hbC9wdWJsaWMvZ2VuL3Byb3RvL25hbWVzcGFjZS9jbG91ZC9jb21wdXRlL3YxYmV0YWIGcHJvdG8z");

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy
 */
export type UsagePolicy = Message<"namespace.cloud.compute.v1beta.UsagePolicy"> & {
  /**
   * If set, limits how many resources can be used concurrently.
   *
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits concurrency_limits = 1;
   */
  concurrencyLimits?: UsagePolicy_ConcurrencyLimits;

  /**
   * If set, limits how many resources can be used in a period.
   *
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits usage_limits = 2;
   */
  usageLimits?: UsagePolicy_UsageLimits;

  /**
   * Overwrites the set of enabled platforms. E.g. linux/arm64, linux/amd64, macos/arm64, windows/amd64.
   *
   * @generated from field: repeated string enabled_platforms = 3;
   */
  enabledPlatforms: string[];

  /**
   * Key is linux/amd64, linux/arm64, macos/arm64 or windows/amd64.
   *
   * @generated from field: map<string, namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits> per_platform_limits = 4;
   */
  perPlatformLimits: { [key: string]: UsagePolicy_PerPlatformLimits };
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.
 * Use `create(UsagePolicySchema)` to create a new message.
 */
export const UsagePolicySchema: GenMessage<UsagePolicy> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits
 */
export type UsagePolicy_ConcurrencyLimits = Message<"namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits"> & {
  /**
   * @generated from field: int64 max_cpu = 1;
   */
  maxCpu: bigint;

  /**
   * @generated from field: int64 max_memory_mb = 2;
   */
  maxMemoryMb: bigint;

  /**
   * @generated from field: int64 max_instance_count = 3;
   */
  maxInstanceCount: bigint;
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits.
 * Use `create(UsagePolicy_ConcurrencyLimitsSchema)` to create a new message.
 */
export const UsagePolicy_ConcurrencyLimitsSchema: GenMessage<UsagePolicy_ConcurrencyLimits> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 0);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits
 */
export type UsagePolicy_UsageLimits = Message<"namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits"> & {
  /**
   * @generated from field: int32 unit_minutes = 1;
   */
  unitMinutes: number;

  /**
   * @generated from field: int32 builds = 2;
   */
  builds: number;

  /**
   * @generated from field: int64 wall_seconds = 3;
   */
  wallSeconds: bigint;
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.UsageLimits.
 * Use `create(UsagePolicy_UsageLimitsSchema)` to create a new message.
 */
export const UsagePolicy_UsageLimitsSchema: GenMessage<UsagePolicy_UsageLimits> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 1);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits
 */
export type UsagePolicy_ShapeLimits = Message<"namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits"> & {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize largest_acceptable_shape = 1;
   */
  largestAcceptableShape?: UsagePolicy_MachineShapeSize;
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits.
 * Use `create(UsagePolicy_ShapeLimitsSchema)` to create a new message.
 */
export const UsagePolicy_ShapeLimitsSchema: GenMessage<UsagePolicy_ShapeLimits> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 2);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits
 */
export type UsagePolicy_PerPlatformLimits = Message<"namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits"> & {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits concurrency_limits = 1;
   */
  concurrencyLimits?: UsagePolicy_ConcurrencyLimits;

  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ShapeLimits shape_limits = 2;
   */
  shapeLimits?: UsagePolicy_ShapeLimits;

  /**
   * List of per-shape concurrency limits.
   *
   * @generated from field: repeated namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits per_shape_limits = 3;
   */
  perShapeLimits: UsagePolicy_PerShapeLimits[];
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.PerPlatformLimits.
 * Use `create(UsagePolicy_PerPlatformLimitsSchema)` to create a new message.
 */
export const UsagePolicy_PerPlatformLimitsSchema: GenMessage<UsagePolicy_PerPlatformLimits> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 3);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize
 */
export type UsagePolicy_MachineShapeSize = Message<"namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize"> & {
  /**
   * @generated from field: int64 cpu = 1;
   */
  cpu: bigint;

  /**
   * @generated from field: int64 memory_mb = 2;
   */
  memoryMb: bigint;
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize.
 * Use `create(UsagePolicy_MachineShapeSizeSchema)` to create a new message.
 */
export const UsagePolicy_MachineShapeSizeSchema: GenMessage<UsagePolicy_MachineShapeSize> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 4);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits
 */
export type UsagePolicy_PerShapeLimits = Message<"namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits"> & {
  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.MachineShapeSize shape = 1;
   */
  shape?: UsagePolicy_MachineShapeSize;

  /**
   * @generated from field: namespace.cloud.compute.v1beta.UsagePolicy.ConcurrencyLimits limits = 2;
   */
  limits?: UsagePolicy_ConcurrencyLimits;
};

/**
 * Describes the message namespace.cloud.compute.v1beta.UsagePolicy.PerShapeLimits.
 * Use `create(UsagePolicy_PerShapeLimitsSchema)` to create a new message.
 */
export const UsagePolicy_PerShapeLimitsSchema: GenMessage<UsagePolicy_PerShapeLimits> = /*@__PURE__*/
  messageDesc(file_proto_namespace_cloud_compute_v1beta_limits, 0, 5);

