// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/compute/v1beta/storage.proto (package namespace.cloud.compute.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.cloud.compute.v1beta.GetCacheVolumeRequest
 */
export const GetCacheVolumeRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetCacheVolumeRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.GetCacheVolumeResponse
 */
export const GetCacheVolumeResponse = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetCacheVolumeResponse",
  () => [
    { no: 1, name: "cache_volume", kind: "message", T: CacheVolume },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.ListCacheVolumesRequest
 */
export const ListCacheVolumesRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.ListCacheVolumesRequest",
  [],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.ListCacheVolumesResponse
 */
export const ListCacheVolumesResponse = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.ListCacheVolumesResponse",
  () => [
    { no: 1, name: "cache_volume", kind: "message", T: CacheVolume, repeated: true },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.CacheVolume
 */
export const CacheVolume = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.CacheVolume",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "metadata", kind: "message", T: VolumeMetadata },
    { no: 4, name: "attachment", kind: "message", T: VolumeAttachment },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.VolumeMetadata
 */
export const VolumeMetadata = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.VolumeMetadata",
  () => [
    { no: 1, name: "created_at", kind: "message", T: Timestamp },
    { no: 2, name: "destroyed_at", kind: "message", T: Timestamp },
    { no: 3, name: "size_mb", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "state", kind: "enum", T: proto3.getEnumType(VolumeMetadata_State) },
  ],
);

/**
 * @generated from enum namespace.cloud.compute.v1beta.VolumeMetadata.State
 */
export const VolumeMetadata_State = proto3.makeEnum(
  "namespace.cloud.compute.v1beta.VolumeMetadata.State",
  [
    {no: 0, name: "STATE_UNKNOWN", localName: "UNKNOWN"},
    {no: 1, name: "STATE_IN_USE", localName: "IN_USE"},
    {no: 2, name: "STATE_AT_REST", localName: "AT_REST"},
    {no: 3, name: "STATE_EXPIRED", localName: "EXPIRED"},
    {no: 4, name: "STATE_ABANDONED", localName: "ABANDONED"},
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.VolumeAttachment
 */
export const VolumeAttachment = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.VolumeAttachment",
  () => [
    { no: 1, name: "attached_to", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "last_attached_at", kind: "message", T: Timestamp },
    { no: 3, name: "last_detached_at", kind: "message", T: Timestamp },
    { no: 4, name: "attached_at", kind: "message", T: Timestamp },
    { no: 5, name: "used_mb_when_attached", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 6, name: "detached_at", kind: "message", T: Timestamp },
    { no: 7, name: "used_mb_when_detached", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 8, name: "container_image_cache", kind: "message", T: ContainerImageCache },
    { no: 9, name: "path_utilization", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: PathUtilization} },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.ContainerImageCache
 */
export const ContainerImageCache = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.ContainerImageCache",
  () => [
    { no: 1, name: "enabled", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.PathUtilization
 */
export const PathUtilization = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.PathUtilization",
  () => [
    { no: 1, name: "cache_framework", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "mount_target", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "utilization_mb", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.GetVolumeTagSummaryRequest
 */
export const GetVolumeTagSummaryRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetVolumeTagSummaryRequest",
  () => [
    { no: 1, name: "tag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.GetVolumeTagSummaryResponse
 */
export const GetVolumeTagSummaryResponse = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetVolumeTagSummaryResponse",
  () => [
    { no: 1, name: "summary", kind: "message", T: TagSummary },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.ListVolumeTagSummariesRequest
 */
export const ListVolumeTagSummariesRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.ListVolumeTagSummariesRequest",
  [],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.ListVolumeTagSummariesResponse
 */
export const ListVolumeTagSummariesResponse = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.ListVolumeTagSummariesResponse",
  () => [
    { no: 1, name: "summaries", kind: "message", T: TagSummary, repeated: true },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.TagSummary
 */
export const TagSummary = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.TagSummary",
  () => [
    { no: 1, name: "tag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "size_mb", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "at_rest", kind: "message", T: CacheVolume, repeated: true },
    { no: 5, name: "in_use", kind: "message", T: CacheVolume, repeated: true },
    { no: 6, name: "generations", kind: "message", T: CacheVolume, repeated: true },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.DestroyCacheVolumeRequest
 */
export const DestroyCacheVolumeRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.DestroyCacheVolumeRequest",
  () => [
    { no: 1, name: "tag", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Cache metadata allows the user to teach Namespace about how a Cache Volume is used.
 * Namespace persists cache metadata and tracks cache utilization for each configured path.
 * To provide cache metadata to Namespace, produce a JSON file inside the Cache Volume
 * at the path `.ns/cache-metadata.json`.
 *
 * @generated from message namespace.cloud.compute.v1beta.CacheMetadata
 */
export const CacheMetadata = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.CacheMetadata",
  () => [
    { no: 1, name: "version", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "updated_at", kind: "message", T: Timestamp },
    { no: 3, name: "user_request", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: CachePathUsage} },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.CachePathUsage
 */
export const CachePathUsage = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.CachePathUsage",
  () => [
    { no: 1, name: "source", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "cache_framework", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "mount_target", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

