// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/compute/v1beta/usage.proto (package namespace.cloud.compute.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message namespace.cloud.compute.v1beta.GetUsageRequest
 */
export const GetUsageRequest = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetUsageRequest",
  () => [
    { no: 1, name: "period_start", kind: "message", T: GetUsageRequest_Date },
    { no: 2, name: "period_end", kind: "message", T: GetUsageRequest_Date },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.GetUsageRequest.Date
 */
export const GetUsageRequest_Date = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetUsageRequest.Date",
  () => [
    { no: 1, name: "year", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "day", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
  {localName: "GetUsageRequest_Date"},
);

/**
 * @generated from message namespace.cloud.compute.v1beta.GetUsageResponse
 */
export const GetUsageResponse = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.GetUsageResponse",
  () => [
    { no: 1, name: "total", kind: "message", T: UsageRecord_Usage },
    { no: 2, name: "per_day", kind: "message", T: UsageRecord, repeated: true },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsageRecord
 */
export const UsageRecord = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.UsageRecord",
  () => [
    { no: 1, name: "year", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "month", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 3, name: "day", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: "total", kind: "message", T: UsageRecord_Usage },
  ],
);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsageRecord.Usage
 */
export const UsageRecord_Usage = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.UsageRecord.Usage",
  () => [
    { no: 1, name: "instance_minutes", kind: "message", T: UsageRecord_Minutes },
    { no: 2, name: "builds", kind: "message", T: UsageRecord_Builds },
  ],
  {localName: "UsageRecord_Usage"},
);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsageRecord.Minutes
 */
export const UsageRecord_Minutes = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.UsageRecord.Minutes",
  () => [
    { no: 1, name: "unit", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "wall", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
  {localName: "UsageRecord_Minutes"},
);

/**
 * @generated from message namespace.cloud.compute.v1beta.UsageRecord.Builds
 */
export const UsageRecord_Builds = proto3.makeMessageType(
  "namespace.cloud.compute.v1beta.UsageRecord.Builds",
  () => [
    { no: 1, name: "count", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "unit_minutes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "wall_minutes", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ],
  {localName: "UsageRecord_Builds"},
);

