// @generated by protoc-gen-es v2.11.0 with parameter "target=ts+dts,import_extension=js"
// @generated from file proto/namespace/cloud/iam/v1beta/authz.proto (package namespace.cloud.iam.v1beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/namespace/cloud/iam/v1beta/authz.proto.
 */
export declare const file_proto_namespace_cloud_iam_v1beta_authz: GenFile;

/**
 * Defines a permission grant on a resource. Permissions are used to restrict
 * what a token is allowed to do.
 *
 * See https://namespace.so/docs/security/permissions for a list of available
 * resource types and actions.
 *
 * @generated from message namespace.cloud.iam.v1beta.Permission
 */
export declare type Permission = Message<"namespace.cloud.iam.v1beta.Permission"> & {
  /**
   * The type of resource this permission applies to, e.g. "instance",
   * "vault/object", "token/revokable".
   *
   * @generated from field: string resource_type = 1;
   */
  resourceType: string;

  /**
   * The specific resource ID, or empty for all resources of this type.
   *
   * @generated from field: string resource_id = 2;
   */
  resourceId: string;

  /**
   * The set of actions allowed on the resource, e.g. "create", "list",
   * "describe".
   *
   * @generated from field: repeated string actions = 3;
   */
  actions: string[];
};

/**
 * Describes the message namespace.cloud.iam.v1beta.Permission.
 * Use `create(PermissionSchema)` to create a new message.
 */
export declare const PermissionSchema: GenMessage<Permission>;

/**
 * Represents a single access check: a specific action on a specific resource.
 *
 * @generated from message namespace.cloud.iam.v1beta.Access
 */
export declare type Access = Message<"namespace.cloud.iam.v1beta.Access"> & {
  /**
   * @generated from field: string resource_type = 1;
   */
  resourceType: string;

  /**
   * @generated from field: string resource_id = 2;
   */
  resourceId: string;

  /**
   * @generated from field: string action = 3;
   */
  action: string;
};

/**
 * Describes the message namespace.cloud.iam.v1beta.Access.
 * Use `create(AccessSchema)` to create a new message.
 */
export declare const AccessSchema: GenMessage<Access>;

/**
 * Returned as an error detail when a request is denied due to insufficient
 * permissions. Lists all the permissions that were missing.
 *
 * @generated from message namespace.cloud.iam.v1beta.PermissionDeniedError
 */
export declare type PermissionDeniedError = Message<"namespace.cloud.iam.v1beta.PermissionDeniedError"> & {
  /**
   * The list of access permissions that the caller was missing.
   *
   * @generated from field: repeated namespace.cloud.iam.v1beta.Access missing_access_permissions = 1;
   */
  missingAccessPermissions: Access[];
};

/**
 * Describes the message namespace.cloud.iam.v1beta.PermissionDeniedError.
 * Use `create(PermissionDeniedErrorSchema)` to create a new message.
 */
export declare const PermissionDeniedErrorSchema: GenMessage<PermissionDeniedError>;

