// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/cloud/iam/v1beta/tokens.proto (package namespace.cloud.iam.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";
import { Permission } from "./authz_pb.js";

/**
 * @generated from message namespace.cloud.iam.v1beta.IssueIdTokenRequest
 */
export const IssueIdTokenRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.IssueIdTokenRequest",
  () => [
    { no: 1, name: "audience", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.IssueIdTokenResponse
 */
export const IssueIdTokenResponse = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.IssueIdTokenResponse",
  () => [
    { no: 1, name: "id_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.IssueTenantTokenRequest
 */
export const IssueTenantTokenRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.IssueTenantTokenRequest",
  () => [
    { no: 1, name: "tenant_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "duration_secs", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "policies", kind: "message", T: TenantTokenPolicy, repeated: true },
    { no: 5, name: "access", kind: "message", T: AccessPolicy },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.AccessPolicy
 */
export const AccessPolicy = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.AccessPolicy",
  () => [
    { no: 1, name: "grants", kind: "message", T: Permission, repeated: true },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.IssueTenantTokenResponse
 */
export const IssueTenantTokenResponse = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.IssueTenantTokenResponse",
  () => [
    { no: 1, name: "bearer_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.TenantTokenPolicy
 */
export const TenantTokenPolicy = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.TenantTokenPolicy",
  () => [
    { no: 1, name: "policy_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.CreateRevokableTokenRequest
 */
export const CreateRevokableTokenRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.CreateRevokableTokenRequest",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "expires_at", kind: "message", T: Timestamp },
    { no: 4, name: "policies", kind: "message", T: TenantTokenPolicy, repeated: true },
    { no: 5, name: "access", kind: "message", T: AccessPolicy },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.CreateRevokableTokenResponse
 */
export const CreateRevokableTokenResponse = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.CreateRevokableTokenResponse",
  () => [
    { no: 1, name: "bearer_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "token", kind: "message", T: RevokableToken },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.RevokeRevokableTokenRequest
 */
export const RevokeRevokableTokenRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.RevokeRevokableTokenRequest",
  () => [
    { no: 1, name: "token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.ListRevokableTokensRequest
 */
export const ListRevokableTokensRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.ListRevokableTokensRequest",
  () => [
    { no: 1, name: "pagination_cursor", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
    { no: 2, name: "max_entries", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 3, name: "include_revoked", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.ListRevokableTokensResponse
 */
export const ListRevokableTokensResponse = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.ListRevokableTokensResponse",
  () => [
    { no: 1, name: "tokens", kind: "message", T: RevokableToken, repeated: true },
    { no: 2, name: "pagination_cursor", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.RevokableToken
 */
export const RevokableToken = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.RevokableToken",
  () => [
    { no: 1, name: "token_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "tenant_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "created_at", kind: "message", T: Timestamp },
    { no: 6, name: "expires_at", kind: "message", T: Timestamp },
    { no: 7, name: "revoked_at", kind: "message", T: Timestamp },
    { no: 8, name: "revoked_by_actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 9, name: "creator_actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest
 */
export const BatchRevokeRevokableTokenRequest = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenRequest",
  () => [
    { no: 1, name: "before", kind: "message", T: Timestamp },
    { no: 2, name: "created_by_actor_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenResponse
 */
export const BatchRevokeRevokableTokenResponse = proto3.makeMessageType(
  "namespace.cloud.iam.v1beta.BatchRevokeRevokableTokenResponse",
  () => [
    { no: 1, name: "revoked_token_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

