// @generated by protoc-gen-es v1.3.0 with parameter "target=js+ts+dts"
// @generated from file proto/namespace/private/images/baseimage.proto (package namespace.private.images.v1beta, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum namespace.private.images.v1beta.ReleaseStage
 */
export enum ReleaseStage {
  /**
   * @generated from enum value: STAGE_UNKNOWN = 0;
   */
  STAGE_UNKNOWN = 0,

  /**
   * @generated from enum value: PRODUCTION = 1;
   */
  PRODUCTION = 1,

  /**
   * @generated from enum value: CANARY = 2;
   */
  CANARY = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ReleaseStage)
proto3.util.setEnumType(ReleaseStage, "namespace.private.images.v1beta.ReleaseStage", [
  { no: 0, name: "STAGE_UNKNOWN" },
  { no: 1, name: "PRODUCTION" },
  { no: 2, name: "CANARY" },
]);

/**
 * @generated from enum namespace.private.images.v1beta.DeprecatedReleaseChannel
 */
export enum DeprecatedReleaseChannel {
  /**
   * @generated from enum value: CHANNEL_UNKNOWN = 0;
   */
  CHANNEL_UNKNOWN = 0,

  /**
   * @generated from enum value: STABLE = 1;
   */
  STABLE = 1,

  /**
   * @generated from enum value: EDGE = 2;
   */
  EDGE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(DeprecatedReleaseChannel)
proto3.util.setEnumType(DeprecatedReleaseChannel, "namespace.private.images.v1beta.DeprecatedReleaseChannel", [
  { no: 0, name: "CHANNEL_UNKNOWN" },
  { no: 1, name: "STABLE" },
  { no: 2, name: "EDGE" },
]);

/**
 * BaseImage describes a Namespace-managed image that is used by one of the various applications built on top of the platform.
 * The same schema is used to define base images used by Linux, and by MacOS.
 *
 * @generated from message namespace.private.images.v1beta.BaseImage
 */
export class BaseImage extends Message<BaseImage> {
  /**
   * Base Image unique identifier.
   *
   * @generated from field: string id = 8;
   */
  id = "";

  /**
   * Deprecated. Use id instead.
   *
   * @generated from field: string ref = 1;
   */
  ref = "";

  /**
   * Corresponds to InstanceShape.os ("linux" or "macos").
   *
   * @generated from field: string os = 2;
   */
  os = "";

  /**
   * E.g. Sonoma, Ubuntu LTS
   *
   * @generated from field: string os_name = 3;
   */
  osName = "";

  /**
   * E.g. 14.4.1
   *
   * @generated from field: string os_version = 4;
   */
  osVersion = "";

  /**
   * A description used for administration purposes.
   *
   * @generated from field: string description = 5;
   */
  description = "";

  /**
   * When the image was last updated.
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  /**
   * The set of software packages that are included; e.g.
   * Docker, Rust, Java, Podman, etc.
   *
   * @generated from field: repeated namespace.private.images.v1beta.Package packages = 7;
   */
  packages: Package[] = [];

  /**
   * The set of software package versions that are set to be default.
   *
   * @generated from field: repeated namespace.private.images.v1beta.Package default_packages = 11;
   */
  defaultPackages: Package[] = [];

  /**
   * Whether this image includes pre-release software.
   * Whether this is a production image, or an image being canaried.
   *
   * @generated from field: namespace.private.images.v1beta.ReleaseStage release_stage = 9;
   */
  releaseStage = ReleaseStage.STAGE_UNKNOWN;

  /**
   * Set of features that the image supports.
   *
   * @generated from field: repeated string features = 10;
   */
  features: string[] = [];

  /**
   * @generated from field: namespace.private.images.v1beta.DeprecatedReleaseChannel release_channel = 12 [deprecated = true];
   * @deprecated
   */
  releaseChannel = DeprecatedReleaseChannel.CHANNEL_UNKNOWN;

  constructor(data?: PartialMessage<BaseImage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.private.images.v1beta.BaseImage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 8, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 1, name: "ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "os", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "os_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "os_version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "updated_at", kind: "message", T: Timestamp },
    { no: 7, name: "packages", kind: "message", T: Package, repeated: true },
    { no: 11, name: "default_packages", kind: "message", T: Package, repeated: true },
    { no: 9, name: "release_stage", kind: "enum", T: proto3.getEnumType(ReleaseStage) },
    { no: 10, name: "features", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 12, name: "release_channel", kind: "enum", T: proto3.getEnumType(DeprecatedReleaseChannel) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BaseImage {
    return new BaseImage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BaseImage {
    return new BaseImage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BaseImage {
    return new BaseImage().fromJsonString(jsonString, options);
  }

  static equals(a: BaseImage | PlainMessage<BaseImage> | undefined, b: BaseImage | PlainMessage<BaseImage> | undefined): boolean {
    return proto3.util.equals(BaseImage, a, b);
  }
}

/**
 * @generated from message namespace.private.images.v1beta.Package
 */
export class Package extends Message<Package> {
  /**
   * E.g. "Xcode", "iOS SDK", aws-cli, Rust, Docker, etc.
   *
   * @generated from field: string name = 1;
   */
  name = "";

  /**
   * Type of installation (e.g. system, pre-installed for Ubuntu or simruntime, Xcode for MacOS)
   *
   * @generated from field: string type = 2;
   */
  type = "";

  /**
   * E.g. 14.3
   *
   * @generated from field: string version = 3;
   */
  version = "";

  constructor(data?: PartialMessage<Package>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.private.images.v1beta.Package";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "version", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Package {
    return new Package().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Package {
    return new Package().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Package {
    return new Package().fromJsonString(jsonString, options);
  }

  static equals(a: Package | PlainMessage<Package> | undefined, b: Package | PlainMessage<Package> | undefined): boolean {
    return proto3.util.equals(Package, a, b);
  }
}

/**
 * @generated from message namespace.private.images.v1beta.ResolvedBaseImage
 */
export class ResolvedBaseImage extends Message<ResolvedBaseImage> {
  /**
   * Specification of Base Image.
   *
   * @generated from field: namespace.private.images.v1beta.BaseImage spec = 1;
   */
  spec?: BaseImage;

  /**
   * Status of Base Image.
   *
   * @generated from field: namespace.private.images.v1beta.BaseImageStatus status = 2;
   */
  status?: BaseImageStatus;

  constructor(data?: PartialMessage<ResolvedBaseImage>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.private.images.v1beta.ResolvedBaseImage";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "spec", kind: "message", T: BaseImage },
    { no: 2, name: "status", kind: "message", T: BaseImageStatus },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResolvedBaseImage {
    return new ResolvedBaseImage().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResolvedBaseImage {
    return new ResolvedBaseImage().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResolvedBaseImage {
    return new ResolvedBaseImage().fromJsonString(jsonString, options);
  }

  static equals(a: ResolvedBaseImage | PlainMessage<ResolvedBaseImage> | undefined, b: ResolvedBaseImage | PlainMessage<ResolvedBaseImage> | undefined): boolean {
    return proto3.util.equals(ResolvedBaseImage, a, b);
  }
}

/**
 * @generated from message namespace.private.images.v1beta.BaseImageStatus
 */
export class BaseImageStatus extends Message<BaseImageStatus> {
  /**
   * Operating-system dependent image reference.
   *
   * Deprecated, use image_repository and image_digest
   *
   * @generated from field: string image_ref = 1;
   */
  imageRef = "";

  /**
   * When the image was last built.
   *
   * @generated from field: google.protobuf.Timestamp built_at = 2;
   */
  builtAt?: Timestamp;

  /**
   * Do not prewarm this image on nodes, but keep this record for information.
   *
   * @generated from field: bool skip_prewarming = 9;
   */
  skipPrewarming = false;

  /**
   * Image repository *without* the registry hostname. E.g. "namespacelabs.dev/internal/service/githubrunner/container/ubuntu2404".
   *
   * @generated from field: string image_repository = 6;
   */
  imageRepository = "";

  /**
   * Image digest. E.g. "sha256:2036fae18ddb748e5482d9a0c22543e638f99f7e15a0a131a71b6d8d5da5c753"
   *
   * @generated from field: string image_digest = 7;
   */
  imageDigest = "";

  constructor(data?: PartialMessage<BaseImageStatus>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "namespace.private.images.v1beta.BaseImageStatus";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "image_ref", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "built_at", kind: "message", T: Timestamp },
    { no: 9, name: "skip_prewarming", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "image_repository", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "image_digest", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BaseImageStatus {
    return new BaseImageStatus().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BaseImageStatus {
    return new BaseImageStatus().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BaseImageStatus {
    return new BaseImageStatus().fromJsonString(jsonString, options);
  }

  static equals(a: BaseImageStatus | PlainMessage<BaseImageStatus> | undefined, b: BaseImageStatus | PlainMessage<BaseImageStatus> | undefined): boolean {
    return proto3.util.equals(BaseImageStatus, a, b);
  }
}

