// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=js"
// @generated from file proto/namespace/private/git/snapshots.proto (package namespace.private.git.v1beta, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/namespace/private/git/snapshots.proto.
 */
export const file_proto_namespace_private_git_snapshots: GenFile = /*@__PURE__*/
  fileDesc("Citwcm90by9uYW1lc3BhY2UvcHJpdmF0ZS9naXQvc25hcHNob3RzLnByb3RvEhxuYW1lc3BhY2UucHJpdmF0ZS5naXQudjFiZXRhItUBChZQcmVwYXJlU25hcHNob3RSZXF1ZXN0EhYKDnJlcG9zaXRvcnlfdXJsGAEgASgJEgsKA3JlZhgCIAEoCRI4CgRraW5kGAMgASgOMioubmFtZXNwYWNlLnByaXZhdGUuZ2l0LnYxYmV0YS5TbmFwc2hvdEtpbmQSFwoPYWRkaXRpb25hbF9yZWZzGAUgAygJEkMKDnJlZl9yZXNvbHV0aW9uGAYgASgOMisubmFtZXNwYWNlLnByaXZhdGUuZ2l0LnYxYmV0YS5SZWZSZXNvbHV0aW9uIsgBChdQcmVwYXJlU25hcHNob3RSZXNwb25zZRILCgN1cmwYASABKAkSEgoKc2l6ZV9ieXRlcxgCIAEoAxIXCg9yZXNvbHZlZF9jb21taXQYAyABKAkSOAoEa2luZBgEIAEoDjIqLm5hbWVzcGFjZS5wcml2YXRlLmdpdC52MWJldGEuU25hcHNob3RLaW5kEiMKG3Jlc29sdmVkX2FkZGl0aW9uYWxfY29tbWl0cxgFIAMoCRIUCgxyZXNvbHZlZF9yZWYYBiABKAki/wIKHFByZXBhcmVTbmFwc2hvdFJlc3BvbnNlQ2h1bmsSRwoIc25hcHNob3QYASABKAsyNS5uYW1lc3BhY2UucHJpdmF0ZS5naXQudjFiZXRhLlByZXBhcmVTbmFwc2hvdFJlc3BvbnNlElEKBnN0YXR1cxgCIAEoDjJBLm5hbWVzcGFjZS5wcml2YXRlLmdpdC52MWJldGEuUHJlcGFyZVNuYXBzaG90UmVzcG9uc2VDaHVuay5TdGF0dXMSDwoHbWVzc2FnZRgDIAEoCSKxAQoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEiAKHFNUQVRVU19TRVRUSU5HX1VQX1JFUE9TSVRPUlkQARIdChlTVEFUVVNfRkVUQ0hJTkdfUkVGRVJFTkNFEAISHQoZU1RBVFVTX1BSRVBBUklOR19TTkFQU0hPVBADEh0KGVNUQVRVU19VUExPQURJTkdfU05BUFNIT1QQBBIQCgxTVEFUVVNfUkVBRFkQBSphCgxTbmFwc2hvdEtpbmQSHQoZU05BUFNIT1RfS0lORF9VTlNQRUNJRklFRBAAEhYKElNOQVBTSE9UX0tJTkRfQkFSRRABEhoKFlNOQVBTSE9UX0tJTkRfQ09NUExFVEUQAipkCg1SZWZSZXNvbHV0aW9uEh4KGlJFRl9SRVNPTFVUSU9OX1VOU1BFQ0lGSUVEEAASGAoUUkVGX1JFU09MVVRJT05fRVhBQ1QQARIZChVSRUZfUkVTT0xVVElPTl9SRUNFTlQQAjKcAQoSR2l0U25hcHNob3RTZXJ2aWNlEoUBCg9QcmVwYXJlU25hcHNob3QSNC5uYW1lc3BhY2UucHJpdmF0ZS5naXQudjFiZXRhLlByZXBhcmVTbmFwc2hvdFJlcXVlc3QaOi5uYW1lc3BhY2UucHJpdmF0ZS5naXQudjFiZXRhLlByZXBhcmVTbmFwc2hvdFJlc3BvbnNlQ2h1bmswAUJNWktuYW1lc3BhY2VsYWJzLmRldi9pbnRlcm5hbC9wdWJsaWMvZ2VuL3Byb3RvL25hbWVzcGFjZS9wcml2YXRlL2dpdDtnaXR2MWJldGFiBnByb3RvMw");

/**
 * @generated from message namespace.private.git.v1beta.PrepareSnapshotRequest
 */
export type PrepareSnapshotRequest = Message<"namespace.private.git.v1beta.PrepareSnapshotRequest"> & {
  /**
   * Git repository URL accepted by git fetch, e.g.
   * https://github.com/namespacelabs/internal.
   *
   * @generated from field: string repository_url = 1;
   */
  repositoryUrl: string;

  /**
   * Git ref, tag, branch, or commit-ish to check out.
   *
   * @generated from field: string ref = 2;
   */
  ref: string;

  /**
   * @generated from field: namespace.private.git.v1beta.SnapshotKind kind = 3;
   */
  kind: SnapshotKind;

  /**
   * Additional git refs, tags, branches, or commit-ish values to include in the
   * local git packs. These do not affect the checkout target.
   *
   * @generated from field: repeated string additional_refs = 5;
   */
  additionalRefs: string[];

  /**
   * Controls whether the ref is resolved immediately or may reuse a recent
   * resolution. RECENT is only valid when ref is HEAD.
   *
   * @generated from field: namespace.private.git.v1beta.RefResolution ref_resolution = 6;
   */
  refResolution: RefResolution;
};

/**
 * Describes the message namespace.private.git.v1beta.PrepareSnapshotRequest.
 * Use `create(PrepareSnapshotRequestSchema)` to create a new message.
 */
export const PrepareSnapshotRequestSchema: GenMessage<PrepareSnapshotRequest> = /*@__PURE__*/
  messageDesc(file_proto_namespace_private_git_snapshots, 0);

/**
 * @generated from message namespace.private.git.v1beta.PrepareSnapshotResponse
 */
export type PrepareSnapshotResponse = Message<"namespace.private.git.v1beta.PrepareSnapshotResponse"> & {
  /**
   * URL from which the SquashFS image can be downloaded. The server supports
   * HTTP range requests for this URL.
   *
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: int64 size_bytes = 2;
   */
  sizeBytes: bigint;

  /**
   * @generated from field: string resolved_commit = 3;
   */
  resolvedCommit: string;

  /**
   * @generated from field: namespace.private.git.v1beta.SnapshotKind kind = 4;
   */
  kind: SnapshotKind;

  /**
   * @generated from field: repeated string resolved_additional_commits = 5;
   */
  resolvedAdditionalCommits: string[];

  /**
   * @generated from field: string resolved_ref = 6;
   */
  resolvedRef: string;
};

/**
 * Describes the message namespace.private.git.v1beta.PrepareSnapshotResponse.
 * Use `create(PrepareSnapshotResponseSchema)` to create a new message.
 */
export const PrepareSnapshotResponseSchema: GenMessage<PrepareSnapshotResponse> = /*@__PURE__*/
  messageDesc(file_proto_namespace_private_git_snapshots, 1);

/**
 * @generated from message namespace.private.git.v1beta.PrepareSnapshotResponseChunk
 */
export type PrepareSnapshotResponseChunk = Message<"namespace.private.git.v1beta.PrepareSnapshotResponseChunk"> & {
  /**
   * @generated from field: namespace.private.git.v1beta.PrepareSnapshotResponse snapshot = 1;
   */
  snapshot?: PrepareSnapshotResponse;

  /**
   * @generated from field: namespace.private.git.v1beta.PrepareSnapshotResponseChunk.Status status = 2;
   */
  status: PrepareSnapshotResponseChunk_Status;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message namespace.private.git.v1beta.PrepareSnapshotResponseChunk.
 * Use `create(PrepareSnapshotResponseChunkSchema)` to create a new message.
 */
export const PrepareSnapshotResponseChunkSchema: GenMessage<PrepareSnapshotResponseChunk> = /*@__PURE__*/
  messageDesc(file_proto_namespace_private_git_snapshots, 2);

/**
 * @generated from enum namespace.private.git.v1beta.PrepareSnapshotResponseChunk.Status
 */
export enum PrepareSnapshotResponseChunk_Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_SETTING_UP_REPOSITORY = 1;
   */
  SETTING_UP_REPOSITORY = 1,

  /**
   * @generated from enum value: STATUS_FETCHING_REFERENCE = 2;
   */
  FETCHING_REFERENCE = 2,

  /**
   * @generated from enum value: STATUS_PREPARING_SNAPSHOT = 3;
   */
  PREPARING_SNAPSHOT = 3,

  /**
   * @generated from enum value: STATUS_UPLOADING_SNAPSHOT = 4;
   */
  UPLOADING_SNAPSHOT = 4,

  /**
   * @generated from enum value: STATUS_READY = 5;
   */
  READY = 5,
}

/**
 * Describes the enum namespace.private.git.v1beta.PrepareSnapshotResponseChunk.Status.
 */
export const PrepareSnapshotResponseChunk_StatusSchema: GenEnum<PrepareSnapshotResponseChunk_Status> = /*@__PURE__*/
  enumDesc(file_proto_namespace_private_git_snapshots, 2, 0);

/**
 * @generated from enum namespace.private.git.v1beta.SnapshotKind
 */
export enum SnapshotKind {
  /**
   * @generated from enum value: SNAPSHOT_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SNAPSHOT_KIND_BARE = 1;
   */
  BARE = 1,

  /**
   * @generated from enum value: SNAPSHOT_KIND_COMPLETE = 2;
   */
  COMPLETE = 2,
}

/**
 * Describes the enum namespace.private.git.v1beta.SnapshotKind.
 */
export const SnapshotKindSchema: GenEnum<SnapshotKind> = /*@__PURE__*/
  enumDesc(file_proto_namespace_private_git_snapshots, 0);

/**
 * @generated from enum namespace.private.git.v1beta.RefResolution
 */
export enum RefResolution {
  /**
   * @generated from enum value: REF_RESOLUTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: REF_RESOLUTION_EXACT = 1;
   */
  EXACT = 1,

  /**
   * @generated from enum value: REF_RESOLUTION_RECENT = 2;
   */
  RECENT = 2,
}

/**
 * Describes the enum namespace.private.git.v1beta.RefResolution.
 */
export const RefResolutionSchema: GenEnum<RefResolution> = /*@__PURE__*/
  enumDesc(file_proto_namespace_private_git_snapshots, 1);

/**
 * @generated from service namespace.private.git.v1beta.GitSnapshotService
 */
export const GitSnapshotService: GenService<{
  /**
   * @generated from rpc namespace.private.git.v1beta.GitSnapshotService.PrepareSnapshot
   */
  prepareSnapshot: {
    methodKind: "server_streaming";
    input: typeof PrepareSnapshotRequestSchema;
    output: typeof PrepareSnapshotResponseChunkSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_namespace_private_git_snapshots, 0);

